(function(){
"use strict";
if(window.GSC_NATIVE_PLATFORM||!('serviceWorker' in navigator))return;
let running=false;
function approvedBuild(worker){return new Promise((resolve,reject)=>{const channel=new MessageChannel(),timeout=setTimeout(()=>{channel.port1.close();reject(Error('UPDATE_CHECK_TIMEOUT'))},8000);channel.port1.onmessage=event=>{clearTimeout(timeout);channel.port1.close();resolve(event.data?.release||'')};worker.postMessage({type:'GET_APPROVED_RELEASE'},[channel.port2])})}
function control(){let button=document.getElementById('gscDeliveryUpdateButton');if(button)return button;button=document.createElement('button');button.id='gscDeliveryUpdateButton';button.type='button';button.style.cssText='position:fixed!important;right:14px!important;top:max(60px,calc(env(safe-area-inset-top,0px) + 58px))!important;z-index:2147483647!important;min-height:44px!important;padding:10px 16px!important;border:2px solid #31ff00!important;border-radius:12px!important;background:#050705!important;color:#31ff00!important;font:900 14px Arial!important;pointer-events:auto!important';document.body.appendChild(button);return button}
async function check(){if(running||document.hidden)return;running=true;try{const response=await fetch('/release.json?delivery_check='+Date.now(),{cache:'no-store',signal:AbortSignal.timeout(8000)});if(!response.ok)throw Error('RELEASE_UNAVAILABLE');const latest=String((await response.json()).release||'');if(!latest)throw Error('RELEASE_MISSING');let readyTimeout;const registration=await Promise.race([navigator.serviceWorker.ready,new Promise((_,reject)=>{readyTimeout=setTimeout(()=>reject(Error('CONTROLLER_TIMEOUT')),8000)})]).finally(()=>clearTimeout(readyTimeout));const worker=navigator.serviceWorker.controller||registration.active;if(!worker)throw Error('CONTROLLER_MISSING');const approved=await approvedBuild(worker);if(!approved)throw Error('APPROVED_RELEASE_MISSING');const existing=document.getElementById('gscDeliveryUpdateButton');if(approved===latest){if(existing)existing.remove();return}const button=control();button.textContent='ACTUALIZAR';button.disabled=false;button.onclick=()=>{button.disabled=true;button.textContent='ACTUALIZANDO…';if(typeof persist==='function')persist();if(document.getElementById('setupOverlay')?.classList.contains('visible')&&typeof captureVisibleRegistrationValues==='function'){captureVisibleRegistrationValues();syncDraftPlayersFromManualRows({strict:false,renderAfter:false});persistDraftState()}const url=new URL('/index-grupal.html',location.origin);url.searchParams.set('inicio','1');url.searchParams.set('__gscg_build_check','1');url.searchParams.set('app_version',latest);url.searchParams.set('update_check',String(Date.now()));const current=new URL(location.href);for(const key of ['personalEvent','personalAccount','personalKind'])if(current.searchParams.has(key))url.searchParams.set(key,current.searchParams.get(key));location.assign(url.toString())}}catch(error){const button=control();button.textContent='REINTENTAR';button.disabled=false;button.onclick=check;console.warn('MANUAL_UPDATE_DELIVERY',error.message)}finally{running=false}}
check();
navigator.serviceWorker.register('/service-worker.js',{scope:'/',updateViaCache:'none'}).then(registration=>registration.update()).then(check).catch(()=>check());
window.addEventListener('pageshow',check);window.addEventListener('online',check);navigator.serviceWorker.addEventListener('controllerchange',check);document.addEventListener('visibilitychange',()=>{if(!document.hidden)check()});setInterval(check,30000);
})();
