(function(){
"use strict";
if(window.GSC_NATIVE_PLATFORM||!('serviceWorker' in navigator)||window.GSC_DELIVERY_UPDATE_STARTED)return;
window.GSC_DELIVERY_UPDATE_STARTED=true;
let running=false;
async function installedBuild(){
 const visible=document.querySelector('meta[name="gscg-release"]')?.content;
 if(visible)return visible;
 if(typeof caches!=='undefined')try{
  const names=(await caches.keys()).filter(name=>name.startsWith('gscg-mobile-')&&name.includes('-approved-')).reverse();
  for(const name of names){const entry=await(await caches.open(name)).match('/index-grupal.html');if(!entry)continue;const release=(await entry.text()).match(/<meta\s+name=["']gscg-release["']\s+content=["']([^"']+)["']/i)?.[1];if(release)return release}
 }catch{}
 // Old controllers do not understand GET_APPROVED_RELEASE. A valid published
 // release still permits an explicit recovery click; discovery never installs it.
 return '';
}
function control(){if(!document.getElementById('gscDeliveryUpdateStyle')){const style=document.createElement('style');style.id='gscDeliveryUpdateStyle';style.textContent='body:has(#gscDeliveryUpdateButton){padding-top:max(120px,calc(env(safe-area-inset-top,0px) + 120px))!important}body:has(#gscDeliveryUpdateButton) #setupOverlay{padding-top:max(120px,calc(env(safe-area-inset-top,0px) + 120px))!important}body:has(#gscDeliveryUpdateButton) #mandatoryUpdate,body:has(#gscDeliveryUpdateButton) #gscFallbackUpdateButton{display:none!important}';document.body.appendChild(style)}let button=document.getElementById('gscDeliveryUpdateButton');if(button)return button;document.getElementById('gscFallbackUpdateButton')?.remove();document.getElementById('mandatoryUpdate')?.style?.setProperty?.('display','none','important');button=document.createElement('button');button.id='gscDeliveryUpdateButton';button.type='button';button.style.cssText='position:fixed!important;right:14px!important;top:max(60px,calc(env(safe-area-inset-top,0px) + 58px))!important;z-index:2147483647!important;min-height:44px!important;padding:10px 16px!important;border:2px solid #31ff00!important;border-radius:12px!important;background:#050705!important;color:#31ff00!important;font:900 14px Arial!important;pointer-events:auto!important;animation:gscUpdatePulse .8s infinite alternate!important;box-shadow:0 0 15px rgba(49,255,0,.48)!important';document.body.appendChild(button);return button}
async function check(){if(running||document.hidden)return;running=true;try{const response=await fetch('/release.json?delivery_check='+Date.now(),{cache:'no-store',signal:AbortSignal.timeout(8000)});if(!response.ok)throw Error('RELEASE_UNAVAILABLE');const latest=String((await response.json()).release||'');if(!latest)throw Error('RELEASE_MISSING');const approved=await installedBuild();const existing=document.getElementById('gscDeliveryUpdateButton');if(approved&&approved===latest){if(existing)existing.remove();return}const button=control();button.textContent='ACTUALIZAR';button.disabled=false;button.onclick=()=>{button.disabled=true;button.textContent='ACTUALIZANDO…';if(typeof persist==='function')persist();if(document.getElementById('setupOverlay')?.classList.contains('visible')&&typeof captureVisibleRegistrationValues==='function'){captureVisibleRegistrationValues();syncDraftPlayersFromManualRows({strict:false,renderAfter:false});persistDraftState()}const url=new URL('/index-grupal.html',location.origin);url.searchParams.set('inicio','1');url.searchParams.set('__gscg_build_check','1');url.searchParams.set('app_version',latest);url.searchParams.set('update_check',String(Date.now()));const current=new URL(location.href);for(const key of ['personalEvent','personalAccount','personalKind'])if(current.searchParams.has(key))url.searchParams.set(key,current.searchParams.get(key));location.assign(url.toString())}}catch(error){const button=control();button.textContent='REINTENTAR';button.disabled=false;button.onclick=check;console.warn('MANUAL_UPDATE_DELIVERY',error.message)}finally{running=false}}
check();
navigator.serviceWorker.register('/service-worker.js',{scope:'/',updateViaCache:'none'}).then(registration=>registration.update()).then(check).catch(()=>check());
window.addEventListener('pageshow',check);window.addEventListener('online',check);navigator.serviceWorker.addEventListener('controllerchange',check);document.addEventListener('visibilitychange',()=>{if(!document.hidden)check()});setInterval(check,30000);
})();
