(function(root,factory){
  const api=factory();
  if(typeof module!=="undefined"&&module.exports)module.exports=api;
  if(root)root.GSCDots=api;
})(typeof globalThis!=="undefined"?globalThis:this,function(){
  "use strict";

  const EVENTS=Object.freeze({
    birdie:{label:"BIRDIE",description:"1 BAJO PAR · AUTOMÁTICO",points:1,automatic:true},
    eagle:{label:"EAGLE",description:"2 BAJO PAR · AUTOMÁTICO",points:2,automatic:true},
    albatross:{label:"ALBATROS",description:"3 BAJO PAR · AUTOMÁTICO",points:3,automatic:true},
    sandy:{label:"SANDY",description:"PAR O MEJOR DESPUÉS DE BÚNKER",points:1},
    greenie:{label:"GREENIE",description:"MÁS CERCA EN PAR 3 Y PAR O MEJOR",points:1},
    chippie:{label:"CHIPPIE",description:"EMBOCA CHIP DESDE FUERA DEL GREEN",points:1},
    poley:{label:"POLEY",description:"EMBOCA PUTT MÁS LARGO QUE LA BANDERA",points:1},
    barkie:{label:"BARKIE",description:"TOCA ÁRBOL Y HACE PAR O MEJOR",points:1},
    arnie:{label:"ARNIE",description:"PAR SIN FAIRWAY NI GREEN EN REGULACIÓN",points:1},
    ferret:{label:"FERRET · GRUPO",description:"EMBOCA DESDE FUERA DEL GREEN; PUEDE DUPLICAR CHIPPIE",points:1,groupRule:true},
    snake:{label:"SNAKE",description:"TRES PUTTS EN EL GREEN · PUNTO NEGATIVO",points:-1},
    amigo:{label:"AMIGO · GRUPO",description:"EVENTO PERSONALIZADO ACORDADO POR EL GRUPO",points:1,groupRule:true},
    left:{label:"IZQUIERDA · GRUPO",description:"BOLA A LA IZQUIERDA SEGÚN ACUERDO DEL GRUPO",points:1,groupRule:true},
    right:{label:"DERECHA · GRUPO",description:"BOLA A LA DERECHA SEGÚN ACUERDO DEL GRUPO",points:1,groupRule:true}
  });
  const round=(value,digits=2)=>{const factor=10**digits;return Math.round((Number(value)||0)*factor)/factor},validPlayers=players=>Array.isArray(players)?players.filter(player=>player?.id&&player?.name).slice(0,6):[];
  function normalizeLedger(value){const ledger={};for(const[hole,players]of Object.entries(value||{})){const number=Number(hole);if(!Number.isInteger(number)||number<1||number>18||!players||typeof players!=="object")continue;ledger[number]={};for(const[id,events]of Object.entries(players)){const valid=[...new Set((Array.isArray(events)?events:[]).filter(event=>Object.hasOwn(EVENTS,event)&&!EVENTS[event].automatic))];if(valid.length)ledger[number][id]=valid}}return ledger}
  function normalizeConfig(value={}){const eventPoints={},enabledEvents={};for(const[key,definition]of Object.entries(EVENTS)){const candidate=Number(value.eventPoints?.[key]);eventPoints[key]=Number.isFinite(candidate)?Math.max(-20,Math.min(20,Math.trunc(candidate))):definition.points;enabledEvents[key]=typeof value.enabledEvents?.[key]==="boolean"?value.enabledEvents[key]:definition.groupRule!==true}return{enabled:value.enabled===true,unitValue:Math.max(.01,round(value.unitValue||5,2)),currency:value.currency==="USD"?"USD":"GTQ",eventPoints,enabledEvents,ledger:normalizeLedger(value.ledger),settlement:"each_player_pays_point_difference_to_each_rival",tiePolicy:"equal_points_push",rulesVersion:"DOTS_DUAL_CURRENCY_V332"}}
  function toggleEvent(configInput,hole,playerId,event){const config=normalizeConfig(configInput),number=Number(hole),id=String(playerId||"");if(!Number.isInteger(number)||number<1||number>18||!id||!Object.hasOwn(EVENTS,event)||EVENTS[event].automatic||config.enabledEvents[event]!==true)return config;const current=new Set(config.ledger[number]?.[id]||[]);current.has(event)?current.delete(event):current.add(event);const ledger=structuredClone(config.ledger);ledger[number]={...(ledger[number]||{})};if(current.size)ledger[number][id]=[...current];else delete ledger[number][id];return{...config,ledger}}
  function automaticEvents(player,hole,configInput={}){const config=normalizeConfig(configInput),score=player?.holes?.[hole];if(!score||score.status==="x"||!Number.isFinite(Number(score.gross))||!Number.isFinite(Number(score.par)))return[];const diff=Number(score.gross)-Number(score.par),events=diff<=-3?["albatross"]:diff===-2?["eagle"]:diff===-1?["birdie"]:[];return events.filter(event=>config.enabledEvents[event]===true)}
  function settlements(players,balances){const debtors=players.map(player=>({id:player.id,name:player.name,amount:round(-(balances[player.id]||0),2)})).filter(item=>item.amount>.009).sort((a,b)=>b.amount-a.amount),creditors=players.map(player=>({id:player.id,name:player.name,amount:round(balances[player.id]||0,2)})).filter(item=>item.amount>.009).sort((a,b)=>b.amount-a.amount),out=[];let d=0,c=0;while(d<debtors.length&&c<creditors.length){const amount=round(Math.min(debtors[d].amount,creditors[c].amount),2);if(amount)out.push({fromPlayerId:debtors[d].id,fromName:debtors[d].name,toPlayerId:creditors[c].id,toName:creditors[c].name,amount});debtors[d].amount=round(debtors[d].amount-amount,2);creditors[c].amount=round(creditors[c].amount-amount,2);if(debtors[d].amount<=.009)d++;if(creditors[c].amount<=.009)c++}return out}
  function compute(playersInput,configInput={},options={}){
    const players=validPlayers(playersInput),config=normalizeConfig(configInput),holeCount=Math.max(1,Math.min(18,Math.trunc(Number(options.holeCount)||18))),points=Object.fromEntries(players.map(player=>[player.id,0])),holes=[];
    if(!config.enabled||players.length<2)return{ok:false,code:!config.enabled?"DOTS_DISABLED":"DOTS_REQUIRES_2_PLAYERS",config,holes,summaries:[],balances:{},metrics:{completedHoles:0,pendingHoles:0,activeEvents:0,holesWithAwards:0,totalAwards:0,automaticAwards:0,manualAwards:0,positivePoints:0,negativePoints:0,moneyTransferred:0,settlementTotal:0,pointExposurePerPlayer:0,leaderNames:[]},settlements:[]};
    for(let hole=1;hole<=holeCount;hole++){
      const awards=[];for(const player of players){const events=[...automaticEvents(player,hole,config),...(config.ledger[hole]?.[player.id]||[]).filter(event=>config.enabledEvents[event]===true)];for(const event of events){const value=config.eventPoints[event];points[player.id]+=value;awards.push({playerId:player.id,name:player.name,event,label:EVENTS[event].label,description:EVENTS[event].description,points:value,automatic:EVENTS[event].automatic===true,groupRule:EVENTS[event].groupRule===true})}}
      const scoresComplete=players.every(player=>{const score=player?.holes?.[hole];return score&&(score.status==="x"||Number.isFinite(Number(score.gross)))});holes.push({hole,state:scoresComplete?(awards.length?"awarded":"none"):"pending",awards});
    }
    const total=Object.values(points).reduce((sum,value)=>sum+value,0),balances=Object.fromEntries(players.map(player=>[player.id,round((players.length*points[player.id]-total)*config.unitValue,2)])),summaries=players.map(player=>{const events=holes.flatMap(hole=>hole.awards.filter(item=>item.playerId===player.id).map(item=>({...item,hole:hole.hole})));return{playerId:player.id,name:player.name,points:points[player.id],positivePoints:events.filter(item=>item.points>0).reduce((sum,item)=>sum+item.points,0),negativePoints:events.filter(item=>item.points<0).reduce((sum,item)=>sum+item.points,0),balance:balances[player.id],events}}),awards=holes.flatMap(item=>item.awards),bestPoints=Math.max(0,...summaries.map(item=>item.points)),hasPosition=summaries.some(item=>item.points!==bestPoints),metrics={completedHoles:holes.filter(item=>item.state!=="pending").length,pendingHoles:holes.filter(item=>item.state==="pending").length,activeEvents:Object.values(config.enabledEvents).filter(Boolean).length,holesWithAwards:holes.filter(item=>item.awards.length).length,totalAwards:awards.length,automaticAwards:awards.filter(item=>item.automatic).length,manualAwards:awards.filter(item=>!item.automatic).length,positivePoints:awards.filter(item=>item.points>0).reduce((sum,item)=>sum+item.points,0),negativePoints:awards.filter(item=>item.points<0).reduce((sum,item)=>sum+item.points,0),moneyTransferred:round(awards.reduce((sum,item)=>sum+Math.abs(item.points),0)*config.unitValue*Math.max(0,players.length-1),2),settlementTotal:round(Object.values(balances).filter(value=>value>0).reduce((sum,value)=>sum+value,0),2),pointExposurePerPlayer:round(config.unitValue*Math.max(0,players.length-1),2),leaderNames:hasPosition?summaries.filter(item=>item.points===bestPoints).map(item=>item.name):[]};
    return{ok:true,config,holes,summaries,points,balances,metrics,settlements:settlements(players,balances)};
  }
  return Object.freeze({EVENTS,normalizeConfig,toggleEvent,automaticEvents,compute});
});
