(function(){'use strict';
const el=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let cursor={},busy=false,hasMore=false,items=new Map();
function render(){const groups=new Map();for(const row of items.values()){const key=row.snapshot.tournament||row.snapshot.groupLabel||'GRUPOS';if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row)}el('rounds').innerHTML=[...groups].map(([name,rows])=>'<section><h2>'+esc(name)+'</h2>'+rows.sort((a,b)=>String(b.snapshot.playedAt).localeCompare(String(a.snapshot.playedAt))).map(row=>{const s=row.snapshot;return '<article data-round="'+esc(row.source+':'+row.id)+'"><h3>'+esc(s.groupLabel)+'</h3><p>'+esc(s.course)+' · '+esc(s.playedAt)+' · '+esc(row.source==='lab'?'LABORATORIO':'PRODUCCIÓN')+'</p><p>ID DE RONDA</p><output>'+esc(row.code)+'</output><p>'+esc(s.status)+' · Recibida: '+esc(row.received_at)+'</p><button data-copy>COPIAR ID</button><button data-scores>SCORES · GENERAL</button><button data-categories>SCORES · CATEGORÍAS</button><section data-details hidden></section></article>'}).join('')+'</section>').join('');el('more').hidden=!hasMore;
for(const card of el('rounds').querySelectorAll('[data-round]')){const row=items.get(card.dataset.round);card.querySelector('[data-copy]').onclick=async()=>{try{await navigator.clipboard.writeText(row.code);el('status').textContent='ID COPIADO'}catch{el('status').textContent='ID: '+row.code}};card.querySelector('[data-scores]').onclick=()=>scores(card,row,false);card.querySelector('[data-categories]').onclick=()=>scores(card,row,true)}}
function scores(card,row,categories){const target=card.querySelector('[data-details]'),players=row.snapshot.players;let category='';const paint=()=>{target.hidden=false;target.innerHTML=(categories?'<label>CATEGORÍA <select><option value="">TODAS</option>'+[...new Set(players.map(p=>p.tournamentCategory||'SIN CATEGORÍA'))].map(c=>'<option '+(c===category?'selected':'')+'>'+esc(c)+'</option>').join('')+'</select></label>':'')+'<table><thead><tr><th>JUGADOR</th><th>GROSS</th><th>NET</th><th>PUNTOS</th><th>HOYOS</th></tr></thead><tbody>'+players.map((p,index)=>({p,index})).filter(({p})=>!category||(p.tournamentCategory||'SIN CATEGORÍA')===category).map(({p,index})=>'<tr><td>'+esc(p.name)+'</td><td>'+esc(p.totals?.gross)+'</td><td>'+esc(p.totals?.net)+'</td><td>'+esc(row.snapshot.mode==='universales'?p.totals?.universalesPoints:p.totals?.stablefordPoints)+'</td><td><button data-player="'+index+'">VER</button></td></tr>').join('')+'</tbody></table>';target.querySelector('select')?.addEventListener('change',e=>{category=e.target.value;paint()});target.querySelectorAll('[data-player]').forEach(b=>b.onclick=()=>window.GSCScoresUI.detail(players[Number(b.dataset.player)],row.snapshot,row.snapshot.tournament||row.snapshot.groupLabel))};paint()}
async function load(reset=false,signal,preserve=false){if(busy)return{ok:true};busy=true;try{const response=await fetch('/api/round-directory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'list',cursor:reset?{}:cursor}),cache:'no-store',signal}),data=await response.json();if(!response.ok||!data.ok)throw new Error(data.code||'ROUND_DIRECTORY_UNAVAILABLE');const initial=items.size===0;if(reset&&!preserve){items=new Map();cursor={}}for(const row of data.items||[])items.set(row.source+':'+row.id,row);if(!preserve||initial){cursor=data.next||{};hasMore=!!data.hasMore;}render();el('status').textContent=(data.partial?'LISTA PARCIAL · REINTENTANDO EL OTRO SERVIDOR':'RONDAS ACTUALIZADAS')+' · '+items.size+' recibidas';return{ok:true,partial:data.partial}}catch(e){el('status').textContent='NO SE PUDO ACTUALIZAR · '+e.message;return{ok:false}}finally{busy=false}}
el('refresh').onclick=()=>load(true);el('more').onclick=()=>load(false);window.GSCDirectoryAutoRefresh.create({refresh:async signal=>{let result=await load(true,signal);while(result.ok&&!result.partial&&hasMore&&!signal.aborted)result=await load(false,signal);return result},delay:15000,timeout:10000}).start();
})();
