(function(root){'use strict';
 const prefix='oneuse_',stateKey='golf-score-card-gt-live-control-v1',mapKey='gsc-one-use-live-events-v1';
 const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
 function stored(key){try{return JSON.parse(root.localStorage.getItem(key)||'{}')}catch{return {}}}
 async function request(action,payload,secret=''){try{const headers={'Content-Type':'application/json'};if(secret)headers.Authorization='LivePublisher '+secret;const response=await root.fetch('/api/live-share',{method:'POST',credentials:'same-origin',cache:'no-store',headers,body:JSON.stringify({action,...payload})});const body=await response.json();return{...body,ok:response.ok&&body.ok===true}}catch{return{ok:false,code:'NETWORK_ERROR'}}}
 function publisher(kind,eventId){const account=root.GSCPersonalEvents?.storageSuffix(),sources=[...(account&&account!=='anonymous'&&!root.GSC_PERSONAL_ACCOUNT?[stored('gscg-personal:'+account+':'+stateKey)]:[]),stored(stateKey)],stream=sources.map(data=>kind==='private'?data.privateStream:data.stream).find(candidate=>candidate?.tournamentId===eventId);return uuid.test(String(eventId||''))&&stream?.tournamentId===eventId&&stream?.publisherSecret?stream:null}
 function remember(eventId,eventKind){const map=stored(mapKey);map[prefix+eventId]={eventId,eventKind};root.localStorage.setItem(mapKey,JSON.stringify(map))}
 function descriptor(key){if(!String(key).startsWith(prefix)||!uuid.test(String(key).slice(prefix.length)))return null;return stored(mapKey)[key]||null}
 async function read(key,payload={}){const event=descriptor(key);return event?request('read',{...event,...payload}):{ok:false,code:'LIVE_SHARE_SESSION_REQUIRED'}}
 async function open(){const url=new URL(root.location.href),eventId=url.searchParams.get('liveEvent'),eventKind=url.searchParams.get('liveKind')||'tournament';if(!uuid.test(eventId||''))return null;const code=new URLSearchParams(url.hash.slice(1)).get('code');let result;
 if(code){result=await request('redeem',{eventId,eventKind,code});if(!result.ok){const existing=await request('read',{eventId,eventKind});if(!existing.ok)return result;result=existing}url.hash='';root.history.replaceState(null,'',url.toString())}else{result=await request('read',{eventId,eventKind});if(!result.ok)return result}
 remember(eventId,eventKind);return{ok:true,kind:'general',token:prefix+eventId,eventKind}}
 let returnFocus=null;function shareKeys(event){const panel=root.document.getElementById('gscOneUseShare');if(!panel)return;if(event.key==='Escape'){event.preventDefault();closePanel()}else if(event.key==='Tab'){const nodes=[...panel.querySelectorAll('button,a[href]')],first=nodes[0],last=nodes.at(-1);if(event.shiftKey&&root.document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&root.document.activeElement===last){event.preventDefault();first.focus()}}}function closePanel(){const panel=root.document.getElementById('gscOneUseShare');if(!panel)return;panel.remove();root.document.removeEventListener('keydown',shareKeys);returnFocus?.focus({preventScroll:true})}
 function finishShare(){closePanel();root.GSCPrivateRounds?.close()}
 async function share(kind,eventId,name){const member=publisher(kind,eventId);if(!member)return{ok:false,code:'LIVE_SHARE_PLAYER_REQUIRED'};const personal=root.GSCPersonalEvents?.descriptor?.('personal_'+eventId),coded=!!personal,result=coded?await root.GSCPersonalEvents.request('share-code',{eventId,eventKind:kind}):await request('create',{eventId,eventKind:kind},member.publisherSecret);if(!result.ok)return result;const url=new URL('/code-entry.html',root.location.origin);url.searchParams.set('visitor','1');if(!coded){url.searchParams.set('liveEvent',eventId);url.searchParams.set('liveKind',kind);}const message=(kind==='private'?'Ronda ':'Torneo ')+(result.name||name||'LIVE')+'\nCódigo de un solo uso: '+result.code+'\n'+url.toString();closePanel();returnFocus=root.document.activeElement;const panel=root.document.createElement('div');panel.id='gscOneUseShare';panel.className='scores-detail-backdrop';panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-label','Compartir LIVE');panel.innerHTML='<section class="scores-detail"><button type="button" data-close-share aria-label="Cerrar">X</button><h3>COMPARTIR LIVE</h3><p>CÓDIGO DE UN SOLO USO</p><output class="one-use-code"></output><p data-share-link></p><p>Se consume al primer ingreso. Quien lo use conserva su sesión de lectura.</p><a class="one-use-send" target="_blank" rel="noopener noreferrer">ENVIAR POR WHATSAPP</a><button type="button" data-native-share>COMPARTIR</button><button type="button" data-copy-share>COPIAR</button><p data-share-status role="status"></p></section>';root.document.body.appendChild(panel);panel.querySelector('output').textContent=result.code;panel.querySelector('[data-share-link]').textContent=url.toString();const send=panel.querySelector('a');send.href='https://wa.me/?text='+encodeURIComponent(message);send.addEventListener('click',()=>root.setTimeout(finishShare,50));panel.querySelector('[data-close-share]').onclick=closePanel;panel.querySelector('[data-native-share]').onclick=async()=>{try{if(root.navigator.share){await root.navigator.share({title:result.name||'LIVE',text:message});finishShare()}else await root.navigator.clipboard.writeText(message)}catch{panel.querySelector('[data-share-status]').textContent='USA WHATSAPP O COPIAR'}};panel.querySelector('[data-copy-share]').onclick=async()=>{try{await root.navigator.clipboard.writeText(message);panel.querySelector('[data-share-status]').textContent='CÓDIGO Y ENLACE COPIADOS'}catch{panel.querySelector('[data-share-status]').textContent='NO SE PUDO COPIAR'}};root.document.addEventListener('keydown',shareKeys);panel.querySelector('[data-close-share]').focus({preventScroll:true});return result}
 root.GSCOneUseLive={share,open,read,publisher,descriptor,close:closePanel};
})(globalThis);
