(function(root,factory){const api=factory(root);if(typeof module==="object"&&module.exports)module.exports=api;if(root?.document)api.start()})(typeof globalThis!=="undefined"?globalThis:this,function(root){
  "use strict";
  const POLL_MS=3000;let access=null,revision=null,timer=null,loading=false,nextCursor=null,pagesLoaded=1,streams=new Map(),tournament=null;
  const $=id=>root.document.getElementById(id),escapeHtml=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
  function parseLiveHash(value){const params=new URLSearchParams(String(value||"").replace(/^#/,""));for(const kind of ["stream","tournament"]){const token=String(params.get(kind)||"");if(/^[A-Za-z0-9_-]{40,100}$/.test(token))return{kind,token}}return null}
  function hubUrl(value){if(!value)return"";const url=new URL("/live-hub.html",root.location.origin),share=new URL(root.location.href).searchParams.get("_vercel_share");if(share)url.searchParams.set("_vercel_share",share);url.hash=`${value.kind==="tournament"?"general":"stream"}=${encodeURIComponent(value.token)}`;return url.toString()}
  function modeLabel(value){return({general:"SCORE CARD",match_play:"MATCH PLAY",four_ball:"FOUR BALL",stableford:"STABLEFORD"})[value]||"SCORE CARD"}
  function statusLabel(value){return value==="officially_closed"?"RONDA FINALIZADA":value==="corrected"?"CORREGIDA":"RONDA EN CURSO"}
  function relation(value){const number=Number(value);if(!Number.isFinite(number))return"";return number===0?"E":number>0?`+${number}`:String(number)}
  function dateTime(value){const date=new Date(value);return Number.isFinite(date.getTime())?new Intl.DateTimeFormat("es-GT",{dateStyle:"medium",timeStyle:"short"}).format(date):"—"}
  function setState(message,tone="",at=null){const target=$("liveViewerState");target.className=`live-state ${tone}`.trim();target.firstElementChild.innerHTML=`<i class="live-dot"></i>${escapeHtml(message)}`;$("liveViewerTime").textContent=at?`ACTUALIZADO ${dateTime(at)}`:""}
  function holeMap(player){return new Map((player?.holes||[]).map(item=>[Number(item.hole),item]))}
  function parMap(snapshot){const map=new Map((snapshot?.courseHoles||[]).map(item=>[Number(item.hole),item.par]));for(const player of snapshot?.players||[])for(const item of player.holes||[])if(item.par)map.set(Number(item.hole),item.par);return map}
  function yardMap(snapshot){return new Map((snapshot?.courseHoles||[]).map(item=>[Number(item.hole),item.yards]))}
  function scoreCell(item,key){if(!item)return"";if(item.explicitX)return key==="gross"?"X":"—";const value=item[key];return Number.isInteger(value)?String(value):""}
  function cellClass(item,key){if(!item)return"";if(key==="relativeToPar"&&Number.isInteger(item.relativeToPar))return item.relativeToPar<0?"filled under":item.relativeToPar>0?"filled over":"filled";return Number.isInteger(item[key])||item.explicitX?"filled":""}
  function playerCard(player,snapshot){const holes=holeMap(player),pars=parMap(snapshot),numbers=Array.from({length:18},(_,index)=>index+1),totals=player.totals||{};return`<section class="player-live"><div class="player-title"><strong>${escapeHtml(player.name)}</strong><small>HCP ${escapeHtml(player.handicap)} · ${escapeHtml(player.tee)}</small></div><div class="score-scroll"><table class="score-live"><thead><tr><th>HOYO</th>${numbers.map(hole=>`<th>${hole}</th>`).join("")}</tr></thead><tbody><tr><td>PAR</td>${numbers.map(hole=>`<td>${escapeHtml(pars.get(hole)||"")}</td>`).join("")}</tr><tr><td>GROSS</td>${numbers.map(hole=>{const item=holes.get(hole);return`<td class="${cellClass(item,"gross")}">${scoreCell(item,"gross")}</td>`}).join("")}</tr><tr><td>NETO</td>${numbers.map(hole=>{const item=holes.get(hole);return`<td class="${cellClass(item,"net")}">${scoreCell(item,"net")}</td>`}).join("")}</tr><tr><td>+ / −</td>${numbers.map(hole=>{const item=holes.get(hole);return`<td class="${cellClass(item,"relativeToPar")}">${item&&!item.explicitX&&Number.isInteger(item.relativeToPar)?relation(item.relativeToPar):""}</td>`}).join("")}</tr></tbody></table></div><div class="player-total"><div><small>HOYOS</small><b>${escapeHtml(totals.holes??0)} / 18</b></div><div><small>GROSS</small><b>${escapeHtml(totals.gross??0)}</b></div><div><small>NETO</small><b>${escapeHtml(totals.net??0)}</b></div><div><small>+ / −</small><b class="${Number(totals.relativeToPar)<0?"under":Number(totals.relativeToPar)>0?"over":""}">${relation(totals.relativeToPar??0)}</b></div>${totals.stablefordPoints===null||totals.stablefordPoints===undefined?"":`<div><small>PUNTOS</small><b>${escapeHtml(totals.stablefordPoints)}</b></div>`}</div></section>`}
  function segmentTotal(player,key,from,to){const items=(player?.holes||[]).filter(item=>item.hole>=from&&item.hole<=to);if(key==="gross")return items.filter(item=>!item.explicitX&&Number.isInteger(item.gross)).reduce((sum,item)=>sum+item.gross,0);return items.reduce((sum,item)=>sum+(Number.isInteger(item.stablefordPoints)?item.stablefordPoints:0),0)}
  function stablefordCard(stream,snapshot){const numbers=Array.from({length:18},(_,index)=>index+1),pars=parMap(snapshot),yards=yardMap(snapshot),players=snapshot.players||[];const scoreRow=(player,key,label,first)=>{const holes=holeMap(player);return`<tr>${first?`<th rowspan="2" class="stable-player">${escapeHtml(player.name)}</th>`:""}<th class="stable-label">${label}</th>${numbers.map(hole=>{const item=holes.get(hole),value=key==="gross"?scoreCell(item,"gross"):scoreCell(item,"stablefordPoints");return`<td class="${cellClass(item,key)}">${value}</td>`}).join("")}</tr>`};const summaryRow=player=>`<tr><th>${escapeHtml(player.name)}</th><td>${segmentTotal(player,"gross",1,9)}</td><td>${segmentTotal(player,"gross",10,18)}</td><td>${segmentTotal(player,"gross",1,18)}</td><td>${segmentTotal(player,"stablefordPoints",1,9)}</td><td>${segmentTotal(player,"stablefordPoints",10,18)}</td><td>${segmentTotal(player,"stablefordPoints",1,18)}</td></tr>`;return`<article class="group-card stableford-live-card" data-stream="${escapeHtml(stream.id)}"><header class="group-head"><div><h2>${escapeHtml(stream.groupLabel||snapshot.groupLabel)}</h2><div class="group-meta">${escapeHtml(snapshot.course)}${snapshot.tournament?` · ${escapeHtml(snapshot.tournament)}`:""} · ${dateTime(snapshot.playedAt)}</div></div><span class="group-badge">STABLEFORD · ${escapeHtml(statusLabel(snapshot.status))}</span></header><div class="score-scroll stable-scroll"><table class="stable-live"><thead><tr><th>JUGADOR</th><th>HOYO</th>${numbers.map(hole=>`<th>${hole}</th>`).join("")}</tr></thead><tbody><tr><th></th><th>PAR</th>${numbers.map(hole=>`<td>${escapeHtml(pars.get(hole)||"")}</td>`).join("")}</tr><tr><th></th><th>YDS</th>${numbers.map(hole=>`<td>${escapeHtml(yards.get(hole)||"")}</td>`).join("")}</tr>${players.map(player=>`${scoreRow(player,"gross","GROSS",true)}${scoreRow(player,"stablefordPoints","PUNTOS",false)}`).join("")}</tbody></table></div><section class="stable-summary"><h3>PUNTOS</h3><div class="score-scroll"><table><thead><tr><th>JUGADOR</th><th>GROSS IN</th><th>GROSS OUT</th><th>GROSS TOTAL</th><th>PUNTOS IN</th><th>PUNTOS OUT</th><th>PUNTOS TOTAL</th></tr></thead><tbody>${players.map(summaryRow).join("")}</tbody></table></div></section></article>`}
  function streamCard(stream){const snapshot=stream?.snapshot;if(!snapshot)return"";if(snapshot.mode==="stableford")return stablefordCard(stream,snapshot);return`<article class="group-card" data-stream="${escapeHtml(stream.id)}"><header class="group-head"><div><h2>${escapeHtml(stream.groupLabel||snapshot.groupLabel)}</h2><div class="group-meta">${escapeHtml(snapshot.course)}${snapshot.tournament?` · ${escapeHtml(snapshot.tournament)}`:""} · ${dateTime(snapshot.playedAt)}</div></div><span class="group-badge">${escapeHtml(modeLabel(snapshot.mode))} · ${escapeHtml(statusLabel(snapshot.status))}</span></header>${(snapshot.players||[]).map(player=>playerCard(player,snapshot)).join("")}</article>`}
  function render(){const values=[...streams.values()].filter(stream=>stream?.snapshot);$("liveViewerGroups").innerHTML=values.length?values.map(streamCard).join(""):`<div class="live-empty">TODAVÍA NO HAY SCORE CARDS PUBLICADAS.</div>`;$("liveLoadMore").hidden=!nextCursor;$("liveViewerSummary").textContent=access?.kind==="tournament"?`${tournament?.name||"TORNEO LIVE"} · ${values.length} GRUPO${values.length===1?"":"S"} CARGADO${values.length===1?"":"S"} · LISTA DINÁMICA SIN MÁXIMO FIJO`:values.length?`${values[0].snapshot?.course||"CAMPO"} · ${values[0].snapshot?.players?.length||0} JUGADOR${values[0].snapshot?.players?.length===1?"":"ES"}`:""}
  async function read(payload){let response;try{response=await root.fetch("/api/live",{method:"POST",headers:{"Content-Type":"application/json"},cache:"no-store",credentials:"same-origin",body:JSON.stringify({action:"read",kind:access.kind,viewerToken:access.token,...payload})})}catch{return{ok:false,code:"NETWORK_ERROR"}}const body=await response.json().catch(()=>({ok:false,code:`HTTP_${response.status}`}));return{...body,ok:response.ok&&body?.ok!==false,status:response.status}}
  function errorMessage(code){return({LIVE_LINK_INVALID:"ENLACE LIVE INVÁLIDO",LIVE_REVOKED:"EL JUGADOR REVOCÓ ESTE ENLACE",LIVE_EXPIRED:"ESTE ENLACE LIVE CADUCÓ",LIVE_RATE_LIMITED:"DEMASIADAS CONSULTAS · REINTENTANDO",NETWORK_ERROR:"SIN SEÑAL · CONSERVANDO LA ÚLTIMA ACTUALIZACIÓN",DATABASE_MIGRATION_REQUIRED:"LIVE AÚN NO ESTÁ ACTIVADO"})[code]||"NO SE PUDO ACTUALIZAR LIVE"}
  async function loadTournamentPage(cursor=null,merge=true){const result=await read({cursor,limit:25});if(!result.ok)return result;tournament=result.tournament||tournament;revision=Number(result.tournament?.revision??result.revision??revision);if(!merge)streams.clear();for(const stream of result.streams||[])streams.set(stream.id,stream);nextCursor=result.nextCursor||null;return result}
  async function refresh(){
    if(loading||!access)return;loading=true;let result;
    if(access.kind==="stream"){result=await read({sinceRevision:revision});if(result.ok&&!result.unchanged&&result.stream){revision=Number(result.stream.revision)||0;streams.set(result.stream.id,result.stream)}}
    else{result=await read({sinceRevision:revision,limit:25});if(result.ok&&!result.unchanged){tournament=result.tournament;revision=Number(result.tournament?.revision)||0;streams.clear();for(const stream of result.streams||[])streams.set(stream.id,stream);nextCursor=result.nextCursor||null;let cursor=nextCursor;for(let page=1;page<pagesLoaded&&cursor;page++){const extra=await loadTournamentPage(cursor,true);if(!extra.ok)break;cursor=nextCursor}}}
    loading=false;if(result?.ok){if(!result.unchanged)render();setState(access.kind==="tournament"?"TORNEO LIVE · ACTUALIZACIÓN CONFIRMADA":"RONDA LIVE · ACTUALIZACIÓN CONFIRMADA","",result.serverAt||new Date().toISOString())}else{const terminal=["LIVE_LINK_INVALID","LIVE_REVOKED","LIVE_EXPIRED"].includes(result?.code);setState(errorMessage(result?.code),terminal?"error":"warning");if(terminal){clearTimeout(timer);return}}
    clearTimeout(timer);timer=setTimeout(refresh,POLL_MS);
  }
  async function loadMore(){if(!nextCursor||loading)return;loading=true;const result=await loadTournamentPage(nextCursor,true);loading=false;if(result.ok){pagesLoaded++;render();setState("MÁS GRUPOS CARGADOS","",result.serverAt)}else setState(errorMessage(result.code),"warning")}
  function start(){access=parseLiveHash(root.location.hash);$("liveLoadMore").addEventListener("click",loadMore);root.addEventListener("hashchange",()=>root.location.reload());root.document.addEventListener("visibilitychange",()=>{if(root.document.visibilityState==="visible")refresh()});root.addEventListener("online",refresh);if(!access){setState("ENLACE LIVE INVÁLIDO","error");$("liveViewerGroups").innerHTML=`<div class="live-empty">SOLICITA UN NUEVO ENLACE A QUIEN LLEVA LA SCORE CARD.</div>`;return false}const hub=$("liveAddHub");if(hub){hub.hidden=false;hub.textContent=access.kind==="tournament"?"ABRIR EN CENTRO LIVE":"AGREGAR A MI CENTRO LIVE";hub.onclick=()=>root.open(hubUrl(access),"_blank","noopener,noreferrer")}refresh();return true}
  return{POLL_MS,parseLiveHash,hubUrl,modeLabel,statusLabel,relation,segmentTotal,stablefordCard,streamCard,start};
});
