(function(root){'use strict';
 const key='gsc-personal-events-v1',prefix='personal_',members=new Map(),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const labels={championship:'CAMPEONATO',a:'A',b:'B',c:'C',d:'D',female:'FEMENINA',senior:'SENIOR',super_senior:'SUPER SENIOR'};
 let events=[],accountCode='',aliases=[];
 function hiddenEvents(){try{return JSON.parse(root.localStorage.getItem('gsc-hidden-events-v1:'+accountCode)||'[]')}catch{return []}}
 function hide(token){const event=descriptor(token);if(!event)return false;root.localStorage.setItem('gsc-hidden-events-v1:'+accountCode,JSON.stringify([...new Set([...hiddenEvents(),event.eventId])]));return true}
 async function canonicalToken(token){if(String(token).startsWith(prefix)){const removed=aliases.find(item=>prefix+item.eventId===token&&item.removed);return removed||hiddenEvents().includes(String(token).slice(prefix.length))?'':token}if(!root.crypto?.subtle)return token;const hash=Array.from(new Uint8Array(await root.crypto.subtle.digest('SHA-256',new TextEncoder().encode(token))),byte=>byte.toString(16).padStart(2,'0')).join('');const item=aliases.find(item=>item.hash===hash);return item?(item.removed||hiddenEvents().includes(item.eventId)?'':prefix+item.eventId):token}
 async function reconcile(items){const result=[];for(const item of items||[]){const token=await canonicalToken(item.token);if(token&&!result.some(saved=>saved.token===token))result.push({...item,token})}return result}

 async function request(action,payload={}){try{if(action!=='identity'&&!accountCode){const started=await request('identity');if(!started.ok)return started}const response=await root.fetch('/api/personal-events',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const result={...await response.json(),ok:response.ok,status:response.status};if(result.ok&&result.personalCode)accountCode=result.personalCode;return result}catch{return{ok:false,code:'NETWORK_ERROR'}}}
 const message=code=>({ACCOUNT_UNAUTHORIZED:'NO SE PUDO PREPARAR EL EVENTO · REINTENTA',ACCOUNT_AUTH_UNAVAILABLE:'SERVICIO DE ACCESO NO DISPONIBLE · REINTENTA',PERSONAL_EVENT_FORBIDDEN:'TU ACCESO A ESTE EVENTO NO ESTÁ AUTORIZADO O FUE REVOCADO',PERSONAL_INVITE_INVALID_OR_USED:'INVITACIÓN INCORRECTA, VENCIDA, UTILIZADA O ASIGNADA A OTRA CUENTA',PERSONAL_EVENT_CLOSED:'EL EVENTO ESTÁ CERRADO',PERSONAL_ACCESS_NOT_ENABLED:'ACCESO PERSONAL AÚN NO ACTIVADO EN LAB',PERSONAL_ASSIGNMENT_INVALID:'REVISA JUGADORES, CATEGORÍAS, HANDICAPS Y GRUPO',LIVE_TOURNAMENT_CAPACITY_REACHED:'CUPO DE 100 JUGADORES COMPLETO',LIVE_JOIN_CODE_INVALID:'CÓDIGO INCORRECTO O TORNEO VENCIDO · REVISA EL WHATSAPP',LIVE_TOURNAMENT_MODE_MISMATCH:'LA MODALIDAD DE TU TARJETA NO COINCIDE CON EL TORNEO',PERSONAL_JOIN_NOT_AVAILABLE:'NO SE PUDO INGRESAR · ACCESO REVOCADO O CUPO COMPLETO',NETWORK_ERROR:'SIN CONEXIÓN · NO SE PUDO VALIDAR TU ACCESO',SHARE_CANCELLED:'COMPARTIR CANCELADO · PUEDES INTENTAR DE NUEVO O CONTINUAR AL SCORE CARD',SHARE_UNAVAILABLE:'NO SE PUDO ABRIR WHATSAPP · PUEDES CONTINUAR AL SCORE CARD',SHARE_WAITING_RETURN:'REGRESA A ESTA PANTALLA DESPUÉS DE COMPARTIR PARA ABRIR EL SCORE CARD'})[code]||'NO SE PUDO COMPLETAR LA ACCIÓN';
 function descriptor(token){try{return JSON.parse(root.localStorage.getItem(key)||'{}')[token]||null}catch{return null}}
 function remember(event){let map={};try{map=JSON.parse(root.localStorage.getItem(key)||'{}')}catch{}const token=prefix+event.eventId;map[token]={eventId:event.eventId,eventKind:event.eventKind};root.localStorage.setItem(key,JSON.stringify(map));return token}
 async function sync(){const result=await request('list');if(!result.ok){events=[];members.clear();accountCode='';return result}members.clear();events=result.events;aliases=result.aliases||[];accountCode=result.accountCode;const items=events.map(event=>{const token=remember(event);members.set(token,{role:event.role,players:event.players,groupLabel:event.groupLabel});return{token,label:event.name,event}});return{ok:true,items:items.filter(item=>item.event.eventKind==='tournament'&&!hiddenEvents().includes(item.event.eventId)),privateItems:items.filter(item=>item.event.eventKind==='private')}}
 async function read(token){const event=descriptor(token);if(!event)return{ok:false,code:'PERSONAL_EVENT_FORBIDDEN'};const result=await request('read',event);if(result.ok){members.set(token,result.membership);result.tournament.createdAt=result.tournament.configuration?.playedAt}else if(['PERSONAL_EVENT_FORBIDDEN','ACCOUNT_UNAUTHORIZED','LIVE_EXPIRED'].includes(result.code))members.delete(token);return result}
 let returnFocus=null,shareReturnArmed=false;function close(){const panel=root.document.getElementById('gscPersonalDialog');if(panel){panel.remove();returnFocus?.focus({preventScroll:true})}}
 function dialog(title,content){close();returnFocus=root.document.activeElement;const backdrop=root.document.createElement('div');backdrop.id='gscPersonalDialog';backdrop.className='scores-detail-backdrop';backdrop.setAttribute('role','dialog');backdrop.setAttribute('aria-modal','true');backdrop.setAttribute('aria-label',title);backdrop.innerHTML='<section class="scores-detail"><button type="button" data-close aria-label="Cerrar">X</button><h3>'+escape(title)+'</h3>'+content+'<p data-status role="status" aria-live="polite"></p></section>';root.document.body.appendChild(backdrop);backdrop.querySelector('[data-close]').onclick=close;backdrop.querySelector('[data-close]').focus();return backdrop}
 function status(panel,result){panel.querySelector('[data-status]').textContent=result.ok?'LISTO':message(result.code);}
 async function identity(){const result=await request('identity'),panel=dialog('MI CÓDIGO PERSONAL',result.ok?'<p>Comparte este código con quien autoriza tu acceso. Identifica tu cuenta; no permite iniciar sesión.</p><output>'+escape(result.personalCode)+'</output>':'');status(panel,result)}
 async function invitation(){const panel=dialog('TENGO UNA INVITACIÓN','<label for="personalInviteCode">CÓDIGO PERSONAL DE INVITACIÓN</label><input id="personalInviteCode" maxlength="32" autocomplete="off"><button class="primary" data-redeem>ENTRAR</button>');panel.querySelector('[data-redeem]').onclick=async()=>{const result=await request('redeem',{code:panel.querySelector('input').value.trim()});status(panel,result);if(result.ok){await sync();close();root.location.assign('/live-hub.html?personalEvent='+encodeURIComponent(result.eventId)+'&personalKind='+result.eventKind)}}}
 function rosterForm(event){const configuration=events.find(item=>item.eventId===event?.eventId)?.configuration,scratch=configuration?.mode==='stableford';return '<label for="personalGroup">GRUPO ASIGNADO</label><input id="personalGroup" maxlength="120">'+Array.from({length:6},(_,i)=>'<fieldset data-player="'+(scratch?'sf':'p')+(i+1)+'"><legend>JUGADOR '+(i+1)+'</legend><input data-name placeholder="Nombre" maxlength="80" aria-label="Nombre jugador '+(i+1)+'"><input data-hcp type="number" min="0" max="54" placeholder="HDCP" '+(scratch?'value="0" readonly':'')+' aria-label="Handicap jugador '+(i+1)+'"><select data-category aria-label="Categoría jugador '+(i+1)+'">'+Object.entries(labels).filter(([k])=>!configuration||configuration.categories.includes(k)).map(([k,v])=>'<option value="'+k+'">'+v+'</option>').join('')+'</select></fieldset>').join('')}
 function roster(panel){return [...panel.querySelectorAll('[data-player]')].filter(el=>el.querySelector('[data-name]').value.trim()).map(el=>({id:el.dataset.player,name:el.querySelector('[data-name]').value.trim(),handicap:el.querySelector('[data-hcp]').value.trim()===''?null:Number(el.querySelector('[data-hcp]').value),tournamentCategory:el.querySelector('[data-category]').value,...(el.dataset.tee?{tee:el.dataset.tee}:{})}))}
 async function invite(event){const panel=dialog('AUTORIZAR PERSONA','<label for="personalRecipient">CÓDIGO PERSONAL DEL DESTINATARIO</label><input id="personalRecipient" maxlength="160"><label for="personalName">NOMBRE DE LA PERSONA</label><input id="personalName" maxlength="80"><label for="personalRole">PERMISO</label><select id="personalRole"><option value="viewer">INVITADO · SOLO LECTURA</option><option value="player">JUGADOR · SU TARJETA</option><option value="scorer">ANOTADOR · SU GRUPO</option></select><details><summary>JUGADORES Y GRUPO ASIGNADOS</summary>'+rosterForm(event)+'</details><button class="primary" data-issue>GENERAR INVITACIÓN PERSONAL</button>');panel.querySelector('[data-issue]').onclick=async()=>{const role=panel.querySelector('#personalRole').value,result=await request('invite',{...event,recipientAccountId:panel.querySelector('#personalRecipient').value.trim(),displayName:panel.querySelector('#personalName').value.trim(),role,groupLabel:panel.querySelector('#personalGroup').value.trim(),players:role==='viewer'?[]:roster(panel)});status(panel,result);if(result.ok){const output=root.document.createElement('output');output.textContent=result.code;panel.querySelector('section').appendChild(output);const copy=root.document.createElement('button');copy.className='primary';copy.textContent='COPIAR INVITACIÓN';copy.onclick=()=>root.navigator.clipboard.writeText('Invitación personal\n'+result.code+'\n'+new URL('/live-hub.html',root.location.origin));panel.querySelector('section').appendChild(copy);panel.querySelector('[data-issue]').disabled=true}}}
 async function configure(event){const current=events.find(item=>item.eventId===event.eventId)?.configuration;if(!current)return;const panel=dialog('CONFIGURACIÓN DEL EVENTO','<label>CAMPO<input data-course maxlength="120" value="'+escape(current.course)+'"></label><label>FECHA<input data-date type="date" value="'+escape(current.playedAt)+'"></label><p>MODALIDAD: '+escape(current.mode)+'</p><fieldset><legend>CATEGORÍAS</legend>'+Object.entries(labels).map(([key,label])=>'<label><input data-category-config type="checkbox" value="'+key+'" '+(current.categories.includes(key)?'checked':'')+'>'+label+'</label>').join('')+'</fieldset><button class="primary" data-save>GUARDAR CONFIGURACIÓN</button>');panel.querySelector('[data-save]').onclick=async()=>{const result=await request('configure',{...event,course:panel.querySelector('[data-course]').value.trim(),playedAt:panel.querySelector('[data-date]').value,mode:current.mode,categories:[...panel.querySelectorAll('[data-category-config]:checked')].map(input=>input.value)});status(panel,result);if(result.ok){await sync();root.dispatchEvent(new CustomEvent('gsc-personal-updated'))}}}
 async function organization(token){
  const event=descriptor(token);if(!event)return;const result=await request('organization',event),panel=dialog('ORGANIZACIÓN','<div data-members></div><div data-history></div>');status(panel,result);if(!result.ok)return;
  const list=panel.querySelector('[data-members]'),closed=events.find(item=>item.eventId===event.eventId)?.status==='closed',roleLabels={organizer:'ORGANIZADOR',player:'JUGADOR',scorer:'ANOTADOR',viewer:'INVITADO · SOLO LECTURA'};
  list.innerHTML=result.members.map(m=>'<p>'+escape(m.display_name)+' · '+escape(roleLabels[m.role])+(m.revoked_at?' · REVOCADO':'')+'</p>'+(!closed&&!m.revoked_at&&m.role!=='viewer'?'<button data-assign-member="'+escape(m.account_id)+'">'+(m.role==='organizer'?'ASIGNAR MI GRUPO':'REASIGNAR GRUPO')+'</button>':'')+(m.role!=='organizer'&&!m.revoked_at?'<button data-revoke="'+escape(m.account_id)+'">REVOCAR ACCESO</button>':'')).join('')+result.invites.filter(i=>!i.consumed_at).map(i=>'<p>'+escape(i.display_name)+' · INVITACIÓN '+(i.revoked_at?'REVOCADA':new Date(i.expires_at)<new Date()?'VENCIDA':'PENDIENTE')+'</p>'+(!i.revoked_at?'<button data-revoke-invite="'+escape(i.id)+'">REVOCAR INVITACIÓN</button>':'')).join('');
  const mutate=async(action,payload)=>{const response=await request(action,{...event,...payload});status(panel,response);if(response.ok){await sync();root.dispatchEvent(new CustomEvent('gsc-personal-updated'));await organization(token)}};
  list.querySelectorAll('[data-revoke]').forEach(b=>b.onclick=()=>mutate('revoke',{accountId:b.dataset.revoke}));list.querySelectorAll('[data-revoke-invite]').forEach(b=>b.onclick=()=>mutate('revoke',{inviteId:b.dataset.revokeInvite}));list.querySelectorAll('[data-assign-member]').forEach(b=>b.onclick=()=>assignment(event,result.members.find(member=>member.account_id===b.dataset.assignMember)));
  if(!closed){const add=root.document.createElement('button');add.className='primary';add.textContent='AUTORIZAR PERSONA';add.onclick=()=>invite(event);list.prepend(add);const settings=root.document.createElement('button');settings.className='secondary';settings.textContent='CONFIGURACIÓN DEL EVENTO';settings.onclick=()=>configure(event);list.prepend(settings);const finish=root.document.createElement('button');finish.className='danger';finish.textContent='CERRAR EVENTO';finish.onclick=()=>mutate('close',{});list.appendChild(finish)}
  const actions={created:'EVENTO CREADO',invite_created:'INVITACIÓN CREADA',invite_consumed:'INVITACIÓN UTILIZADA',access_revoked:'ACCESO REVOCADO',assignment_changed:'ASIGNACIÓN MODIFICADA',configuration_changed:'CONFIGURACIÓN MODIFICADA',closed:'EVENTO CERRADO'};
  const describe=value=>{if(!value)return '';if(value.players)return 'GRUPO '+(value.group||'—')+' · '+value.players.map(player=>player.name+' · HDCP '+player.handicap+' · '+(labels[player.tournamentCategory]||'')).join(' / ');if(value.course)return value.course+' · '+value.playedAt+' · '+(value.categories||[]).map(category=>labels[category]||category).join(', ');return value.role?roleLabels[value.role]:''};
  panel.querySelector('[data-history]').innerHTML='<h4>HISTORIAL DE ORGANIZACIÓN</h4>'+result.history.map(item=>'<details><summary>'+escape(new Date(item.created_at).toLocaleString('es-GT',{timeZone:'America/Guatemala'}))+' · '+escape(actions[item.action]||item.action)+'</summary>'+(item.details?.before?'<p>ANTES: '+escape(describe(item.details.before))+'</p><p>DESPUÉS: '+escape(describe(item.details.after))+'</p>':'<p>'+escape(describe(item.details))+'</p>')+'</details>').join('');

 }
 async function assignment(event,member){const panel=dialog(member?.role==='organizer'?'ASIGNAR MI GRUPO':'REASIGNAR GRUPO',rosterForm(event)+'<button class="primary" data-assign>GUARDAR ASIGNACIÓN</button>');panel.querySelector('#personalGroup').value=member?.group_label||'';[...panel.querySelectorAll('[data-player]')].forEach((field,index)=>{const player=member?.players?.[index];if(player){field.dataset.player=player.id;if(player.tee)field.dataset.tee=player.tee;field.querySelector('[data-name]').value=player.name;field.querySelector('[data-hcp]').value=player.handicap;field.querySelector('[data-category]').value=player.tournamentCategory}});panel.querySelector('[data-assign]').onclick=async()=>{const result=await request('assign',{...event,accountId:member?.account_id,groupLabel:panel.querySelector('#personalGroup').value.trim(),players:roster(panel)});status(panel,result);if(result.ok){await sync();root.dispatchEvent(new CustomEvent('gsc-personal-updated'))}}}
 async function continueToCreatedPrivateCard(panel,event){close();await openAssignedCard(event)}
 function installCreatedPrivateRoundActions(panel,result,eventKind='private',returnTo=''){
  const code=String(result.joinCode||'').trim(),event={eventId:result.eventId,eventKind};
  panel.querySelector('h3').textContent=eventKind==='tournament'?'TORNEO CREADO':'RONDA PRIVADA CREADA';
  panel.querySelector('section').insertAdjacentHTML('beforeend','<p>COMPARTIR CÓDIGO CON LOS JUGADORES</p><output data-private-round-code></output><button class="primary" type="button" data-share-private-round>COMPARTIR POR WHATSAPP</button><button type="button" data-continue-private-round>CONTINUAR AL SCORE CARD</button>');
  panel.querySelector('[data-private-round-code]').textContent=code||'CÓDIGO NO DISPONIBLE';
  const shareUrl=new URL('/index-grupal.html?inicio=1',root.location.origin).toString();
  const messageText='Te invito a '+(eventKind==='tournament'?'el torneo ':'la ronda privada ')+(result.name||'')+'.\nCódigo de acceso: '+code+'\nAbre Golf Score Card GT: '+shareUrl;
  const navigate=()=>{if(returnTo){try{const url=new URL(returnTo,root.location.origin);if(url.origin===root.location.origin&&url.pathname==='/index-grupal.html'){close();root.location.assign(url.toString());return}}catch{}}return continueToCreatedPrivateCard(panel,event)};
  panel.querySelector('[data-continue-private-round]').onclick=navigate;
  panel.querySelector('[data-share-private-round]').onclick=async()=>{
   const shareData={title:result.name||'Ronda privada · Golf Score Card GT',text:messageText,url:shareUrl};
   if(typeof root.navigator?.share==='function'){
    try{await root.navigator.share(shareData);await navigate()}
    catch(error){if(error?.name==='AbortError')status(panel,{ok:false,code:'SHARE_CANCELLED'});else status(panel,{ok:false,code:'SHARE_UNAVAILABLE'})}
    return
   }
   const whatsapp='https://wa.me/?text='+encodeURIComponent(messageText);
   shareReturnArmed=false;
   const onVisibility=()=>{if(root.document.visibilityState==='hidden')shareReturnArmed=true;else if(shareReturnArmed){root.document.removeEventListener('visibilitychange',onVisibility);root.removeEventListener?.('focus',onFocus);shareReturnArmed=false;navigate()}};
   const onFocus=()=>{if(shareReturnArmed)onVisibility()};
   root.document.addEventListener('visibilitychange',onVisibility);root.addEventListener?.('focus',onFocus);
   const opened=root.open?.(whatsapp,'_blank','noopener,noreferrer');
   if(!opened)status(panel,{ok:false,code:'SHARE_UNAVAILABLE'});else status(panel,{ok:false,code:'SHARE_WAITING_RETURN'});
  };
 }
 function presentCreatedTournament(result,returnTo=''){const panel=dialog('TORNEO CREADO','');installCreatedPrivateRoundActions(panel,result,'tournament',returnTo)}
 async function createPrivate(round){const config=round?.configured?round:null,panel=dialog('CREAR RONDA PRIVADA','<label for="personalRoundName">NOMBRE DE LA RONDA</label><input id="personalRoundName" maxlength="120"><label for="personalRoundCourse">CAMPO</label><input id="personalRoundCourse" maxlength="120" value="'+escape(config?.course||'')+'"><label for="personalRoundDate">FECHA</label><input id="personalRoundDate" type="date" value="'+new Intl.DateTimeFormat('en-CA',{timeZone:'America/Guatemala'}).format(new Date())+'"><button class="primary" data-create-private>CREAR RONDA PRIVADA</button>');panel.querySelector('[data-create-private]').onclick=async()=>{const snapshot=config?root.GSCLiveControl.buildLiveSnapshot(config):null,result=await request('create',{eventKind:'private',name:panel.querySelector('#personalRoundName').value.trim(),course:panel.querySelector('#personalRoundCourse').value.trim(),playedAt:panel.querySelector('#personalRoundDate').value,mode:config?.mode||'general',categories:Object.keys(labels),players:snapshot?.players||[],groupLabel:snapshot?.groupLabel||''});status(panel,result);if(result.ok){root.localStorage.setItem('golf-score-card-gt-private-round-v1',JSON.stringify({id:result.eventId,name:result.name,viewerToken:result.viewerToken,joinCode:result.joinCode,creator:true,roundId:config?.registrationDraft?'':config?.id||'',expiresAt:result.expiresAt,personal:true}));await sync();if(config?.registrationDraft){installCreatedPrivateRoundActions(panel,result);return}close();if(config)await root.GSCLiveControl.connectPrivateRound(result.eventId,result.joinCode,config);root.GSCPrivateRounds.openScores(config)}}}
 async function openAssignedCard(event){const result=await request('read',event);if(!result.ok||!result.membership?.players?.length||result.tournament.status==='closed'){const panel=dialog('SCORE CARD ASIGNADA','');status(panel,{ok:false,code:result.code||(result.tournament?.status==='closed'?'PERSONAL_EVENT_CLOSED':'PERSONAL_WRITER_FORBIDDEN')});return false}if(result.membership.role==='organizer'){try{const liveKey='golf-score-card-gt-live-control-v1',prior=JSON.parse(root.localStorage.getItem(liveKey)||'null'),scopedKey='gscg-personal:'+result.accountCode+':'+liveKey;if(prior?.tournamentOwned?.tournamentId===event.eventId){const scoped=JSON.parse(root.localStorage.getItem(scopedKey)||'null');root.localStorage.setItem(scopedKey,JSON.stringify({...scoped,version:1,tournamentOwned:prior.tournamentOwned}))}}catch{}}root.localStorage.setItem('gscg-personal:'+result.accountCode+':gsc-tournament-connect-selection-v1',JSON.stringify({personal:true,id:event.eventId,eventKind:event.eventKind,label:result.tournament.name,mode:result.tournament.configuration.mode,configuration:result.tournament.configuration,groupLabel:result.membership.groupLabel,players:result.membership.players}));const url=new URL('/index-grupal.html',root.location.origin);url.searchParams.set('manual_action','personal-scorecard');url.searchParams.set('personalAccount',result.accountCode);url.searchParams.set('personalEvent',event.eventId);url.searchParams.set('personalKind',event.eventKind);root.location.assign(url.toString());return true}

 function joinTournament(round,onJoined){
  const snapshot=root.GSCLiveControl?.buildLiveSnapshot(round);if(!snapshot)return;
  const panel=dialog('TORNEO ACTIVO','<p>Pega el código que recibiste por WhatsApp del creador del torneo.</p><label for="activeTournamentCode">CÓDIGO DEL TORNEO</label><input id="activeTournamentCode" maxlength="10" autocomplete="off" autocapitalize="characters"><button class="primary" type="button" data-join-active>ENTRAR AL TORNEO</button>');
  panel.querySelector('[data-join-active]').onclick=async()=>{const button=panel.querySelector('[data-join-active]');button.disabled=true;try{const result=await request('join-code',{joinCode:panel.querySelector('input').value.trim(),players:snapshot.players,groupLabel:snapshot.groupLabel,mode:snapshot.mode});status(panel,result);if(!result.ok)return;remember(result);await sync();const connected=await onJoined(result);if(connected){close()}else status(panel,{ok:false,code:'NETWORK_ERROR'})}finally{button.disabled=false}};
  panel.querySelector('input').focus();
 }
 function positions(token,rows,categoryRank){const member=members.get(token);if(!member||!member.players.length)return '';const ids=new Set(member.players.map(p=>p.id));return rows.filter(row=>row.groupLabel===member.groupLabel&&ids.has(row.player.id)).map(row=>'<p>'+escape(row.name)+' · GENERAL '+escape(row.rankLabel||'—')+' · '+escape(labels[row.tournamentCategory]||'')+' '+escape(categoryRank?.(row)||'—')+' · '+escape(row.holes||0)+' HOYOS COMPLETADOS</p>').join('')}
 function membership(token){return members.get(token)}
 root.GSCPersonalEvents={joinTournament,hide,canonicalToken,reconcile,storageSuffix:()=>accountCode||'anonymous',request,message,descriptor,sync,read,identity,invitation,organization,positions,membership,openAssignedCard,createPrivate,presentCreatedTournament,close};
 root.document.addEventListener('keydown',e=>{const panel=root.document.getElementById('gscPersonalDialog');if(!panel)return;if(e.key==='Escape'){e.preventDefault();close()}else if(e.key==='Tab'){const nodes=[...panel.querySelectorAll('button,input,select,a[href],summary')].filter(node=>!node.disabled&&node.getClientRects().length),first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&root.document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&root.document.activeElement===last){e.preventDefault();first.focus()}}});
})(globalThis);
