(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.GSCRoundClosure=api})(typeof globalThis!=="undefined"?globalThis:this,function(){
  const stable=value=>Array.isArray(value)?`[${value.map(stable).join(",")}]`:value&&typeof value==="object"?`{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${stable(value[k])}`).join(",")}}`:JSON.stringify(value);
  const stablefordPoints=(gross,par)=>{const againstPar=gross-par;if(againstPar>=2)return 0;if(againstPar===1)return 1;if(againstPar===0)return 2;if(againstPar===-1)return 3;return 4};
  async function sha256(value){const bytes=new TextEncoder().encode(stable(value)),hash=await crypto.subtle.digest("SHA-256",bytes);return[...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,"0")).join("")}
  function validate(round){if(!round?.configured||!Array.isArray(round.players)||!round.players.length)return{ok:false,code:"ROUND_NOT_CONFIGURED"};for(const p of round.players){for(let h=Math.max(1,p.activeFrom||1);h<=18;h++){const s=p.holes?.[h];if(!s||s.status==="x"||!Number.isInteger(s.gross))return{ok:false,code:"SCORE_PENDING",playerId:p.id,hole:h}}}return{ok:true}}
  async function close(round,{deriveScore,appVersion="unknown",closedAt=new Date().toISOString()}={}){const valid=validate(round);if(!valid.ok)return valid;if(round.officiallyClosedAt)return{ok:true,round,snapshot:round.officialSnapshot,alreadyClosed:true};const snapshot={roundId:round.id,version:Number(round.officialVersion)||1,status:"officially_closed",course:round.course,tournament:round.tournament||null,playedAt:round.createdAt,officiallyClosedAt:closedAt,appVersion,players:round.players.map(p=>({id:p.id,name:p.name,handicap:p.handicap,tee:p.tee,matrix:p.matrix,activeFrom:p.activeFrom||1,holes:Object.fromEntries(Object.keys(p.holes).map(raw=>{const h=Number(raw);return[h,deriveScore?deriveScore(p,h):p.holes[h]]}))}))};snapshot.sha256=await sha256(snapshot);return{ok:true,snapshot,round:{...round,status:"officially_closed",officiallyClosedAt:closedAt,officialVersion:snapshot.version,snapshotHash:snapshot.sha256,officialSnapshot:snapshot}}}
  async function correct(round,{changes=[],reason,authorizedBy,correctedAt=new Date().toISOString(),appVersion="unknown"}={}){if(!round?.officialSnapshot||!round.officiallyClosedAt)return{ok:false,code:"ROUND_NOT_CLOSED"};if(!String(reason||"").trim())return{ok:false,code:"REASON_REQUIRED"};if(!String(authorizedBy||"").trim())return{ok:false,code:"AUTHORIZATION_REQUIRED"};if(!Array.isArray(changes)||!changes.length)return{ok:false,code:"CHANGES_REQUIRED"};const original=structuredClone(round.officialSnapshot),next=structuredClone(original);for(const change of changes){const p=next.players.find(x=>x.id===change.playerId);if(!p)return{ok:false,code:"PLAYER_NOT_FOUND"};const h=Number(change.hole),gross=Number(change.gross);if(!Number.isInteger(h)||h<1||h>18||!Number.isInteger(gross)||gross<1||gross>30)return{ok:false,code:"INVALID_CHANGE"};const old=p.holes?.[h];if(!old)return{ok:false,code:"HOLE_NOT_FOUND"};const strokes=Number(old.strokes)||0,par=Number(old.par),score={...old,gross,status:null,net:gross-strokes,diff:gross-strokes-par};if(next.mode==="stableford")score.points=stablefordPoints(gross,par);p.holes[h]=score}next.version=Number(original.version)+1;next.status="corrected";next.label="Tarjeta corregida";next.correctedAt=correctedAt;next.correction={reason:String(reason).trim(),authorizedBy:String(authorizedBy).trim(),changes:structuredClone(changes),previousSha256:original.sha256};next.appVersion=appVersion;delete next.sha256;next.sha256=await sha256(next);const versions=[...(round.officialVersions||[original]),next];return{ok:true,snapshot:next,round:{...round,status:"corrected",officialVersion:next.version,snapshotHash:next.sha256,officialSnapshot:next,officialVersions:versions}}}
  return{stableStringify:stable,sha256,validate,close,correct};
});
