(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.GSCRoundClosure=api})(typeof globalThis!=="undefined"?globalThis:this,function(){
  const stable=value=>Array.isArray(value)?`[${value.map(stable).join(",")}]`:value&&typeof value==="object"?`{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${stable(value[k])}`).join(",")}}`:JSON.stringify(value);
  function sha256Sync(value){
    const rotate=(value,amount)=>(value>>>amount)|(value<<(32-amount)),maxWord=Math.pow(2,32),words=[];let ascii=unescape(encodeURIComponent(stable(value))),asciiBitLength=ascii.length*8,hash=sha256Sync.h||(sha256Sync.h=[]),constants=sha256Sync.k||(sha256Sync.k=[]),primeCounter=constants.length,result="",isComposite={};
    for(let candidate=2;primeCounter<64;candidate++){if(!isComposite[candidate]){for(let multiple=0;multiple<313;multiple+=candidate)isComposite[multiple]=candidate;hash[primeCounter]=(Math.pow(candidate,.5)*maxWord)|0;constants[primeCounter++]=(Math.pow(candidate,1/3)*maxWord)|0}}
    ascii+="\x80";while(ascii.length%64-56)ascii+="\x00";for(let index=0;index<ascii.length;index++){const code=ascii.charCodeAt(index);if(code>>8)return"";words[index>>2]|=code<<(24-index%4*8)}words[words.length]=asciiBitLength/maxWord|0;words[words.length]=asciiBitLength;
    for(let offset=0;offset<words.length;){const schedule=words.slice(offset,offset+=16),previous=hash;hash=hash.slice(0,8);for(let index=0;index<64;index++){const w15=schedule[index-15],w2=schedule[index-2],a=hash[0],e=hash[4],word=index<16?schedule[index]:(schedule[index-16]+(rotate(w15,7)^rotate(w15,18)^(w15>>>3))+schedule[index-7]+(rotate(w2,17)^rotate(w2,19)^(w2>>>10)))|0;schedule[index]=word;const temp1=(hash[7]+(rotate(e,6)^rotate(e,11)^rotate(e,25))+((e&hash[5])^((~e)&hash[6]))+constants[index]+word)|0,temp2=((rotate(a,2)^rotate(a,13)^rotate(a,22))+((a&hash[1])^(a&hash[2])^(hash[1]&hash[2])))|0;hash=[(temp1+temp2)|0,a,hash[1],hash[2],(hash[3]+temp1)|0,e,hash[5],hash[6]]}for(let index=0;index<8;index++)hash[index]=(hash[index]+previous[index])|0}
    for(let index=0;index<8;index++)for(let byte=3;byte+1;byte--){const next=hash[index]>>(byte*8)&255;result+=(next<16?"0":"")+next.toString(16)}return result
  }
  const stablefordPoints=(gross,par)=>{const againstPar=gross-par;if(againstPar>=2)return 0;if(againstPar===1)return 1;if(againstPar===0)return 2;if(againstPar===-1)return 3;return 4};
  function correctedMatchStatus(players){const api=globalThis.GSCMatchPlay;if(api?.status)return api.status(players);return{valid:false,closed:false,decidedAt:null,label:"MATCH PLAY",resultLabel:"MATCH PLAY"}}
  function correctedFourBallStatus(players){const api=globalThis.GSCFourBall;if(api?.status)return api.status(players);return{valid:false,closed:false,decidedAt:null,label:"FOUR BALL",resultLabel:"FOUR BALL"}}
  function correctedSideGames(players,value){const next=structuredClone(value||{}),apis={skins:globalThis.GSCSkins,wolf:globalThis.GSCWolf,vegas:globalThis.GSCVegas,dots:globalThis.GSCDots};for(const[key,api]of Object.entries(apis)){if(next[key]?.enabled!==true||!api?.compute)continue;const config=api.normalizeConfig(next[key]);next[key]={...config,result:api.compute(players,config)}}return next}
  async function sha256(value){const bytes=new TextEncoder().encode(stable(value)),hash=await crypto.subtle.digest("SHA-256",bytes);return[...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,"0")).join("")}
  function validate(round){
    if(!round?.configured||!Array.isArray(round.players)||!round.players.length)return{ok:false,code:"ROUND_NOT_CONFIGURED"};
    const teamMatch=round.mode==="match_play"||round.mode==="four_ball",limits=Array(round.players.length).fill(18);
    if(round.mode==="match_play"){
      if(![2,4,6].includes(round.players.length)||!round.matchPlay?.closed)return{ok:false,code:"MATCH_NOT_DECIDED"};
      for(let index=0;index<round.players.length;index++){const match=round.matchPlay.matches?.[Math.floor(index/2)]||round.matchPlay,finalHole=Number(match?.decidedAt);if(!Number.isInteger(finalHole)||finalHole<1||finalHole>18)return{ok:false,code:"MATCH_NOT_DECIDED"};limits[index]=finalHole}
    }
    if(round.mode==="four_ball"){
      const finalHole=Number(round.fourBall?.decidedAt);if(![2,4,6].includes(round.players.length)||!round.fourBall?.closed||!Number.isInteger(finalHole)||finalHole<1||finalHole>18)return{ok:false,code:"FOUR_BALL_NOT_DECIDED"};limits.fill(finalHole)
    }
    for(let index=0;index<round.players.length;index++){const p=round.players[index];for(let h=Math.max(1,p.activeFrom||1);h<=limits[index];h++){const s=p.holes?.[h];if(!s||s.status==="x"||!Number.isInteger(s.gross))return{ok:false,code:"SCORE_PENDING",playerId:p.id,hole:h}}}
    const sideGames=correctedSideGames(round.players,round.sideGames),wolf=sideGames.wolf?.result;if(sideGames.wolf?.enabled===true){if(!wolf?.ok)return{ok:false,code:"SIDE_GAME_INVALID",game:"wolf"};const pending=wolf.holes.find(item=>["decision_pending","pending"].includes(item.state));if(pending)return{ok:false,code:"SIDE_GAME_PENDING",game:"wolf",hole:pending.hole}}
    return{ok:true,teamMatch,sideGames}
  }
  function closeBase(round,{deriveScore,appVersion="unknown",closedAt=new Date().toISOString()}={}){const valid=validate(round);if(!valid.ok)return valid;if(round.officiallyClosedAt)return{ok:true,round,snapshot:round.officialSnapshot,alreadyClosed:true};const snapshot={roundId:round.id,version:Number(round.officialVersion)||1,status:"officially_closed",mode:round.mode||"general",courseKey:round.courseKey,course:round.course,tournament:round.tournament||null,sideGames:valid.sideGames||correctedSideGames(round.players,round.sideGames),matchPlay:round.mode==="match_play"?round.matchPlay:null,fourBall:round.mode==="four_ball"?round.fourBall:null,playedAt:round.createdAt,officiallyClosedAt:closedAt,appVersion,players:round.players.map(p=>({id:p.id,name:p.name,handicap:p.handicap,tee:p.tee,matrix:p.matrix,activeFrom:p.activeFrom||1,holes:Object.fromEntries(Object.keys(p.holes).map(raw=>{const h=Number(raw);return[h,deriveScore?deriveScore(p,h):p.holes[h]]}))}))};snapshot.sideGames=correctedSideGames(snapshot.players,snapshot.sideGames);return{ok:true,snapshot,round}}
  async function close(round,options={}){const built=closeBase(round,options);if(!built.ok||built.alreadyClosed)return built;built.snapshot.sha256=await sha256(built.snapshot);return{ok:true,snapshot:built.snapshot,round:{...built.round,sideGames:built.snapshot.sideGames,status:"officially_closed",officiallyClosedAt:built.snapshot.officiallyClosedAt,officialVersion:built.snapshot.version,snapshotHash:built.snapshot.sha256,officialSnapshot:built.snapshot}}}
  function closeSync(round,options={}){const built=closeBase(round,options);if(!built.ok||built.alreadyClosed)return built;built.snapshot.sha256=sha256Sync(built.snapshot);return{ok:true,snapshot:built.snapshot,round:{...built.round,sideGames:built.snapshot.sideGames,status:"officially_closed",officiallyClosedAt:built.snapshot.officiallyClosedAt,officialVersion:built.snapshot.version,snapshotHash:built.snapshot.sha256,officialSnapshot:built.snapshot}}}
  async function correct(round,{changes=[],reason,authorizedBy,correctedAt=new Date().toISOString(),appVersion="unknown"}={}){if(!round?.officialSnapshot||!round.officiallyClosedAt)return{ok:false,code:"ROUND_NOT_CLOSED"};if(!String(reason||"").trim())return{ok:false,code:"REASON_REQUIRED"};if(!String(authorizedBy||"").trim())return{ok:false,code:"AUTHORIZATION_REQUIRED"};if(!Array.isArray(changes)||!changes.length)return{ok:false,code:"CHANGES_REQUIRED"};const original=structuredClone(round.officialSnapshot),next=structuredClone(original);for(const change of changes){const p=next.players.find(x=>x.id===change.playerId);if(!p)return{ok:false,code:"PLAYER_NOT_FOUND"};const h=Number(change.hole),gross=Number(change.gross);if(!Number.isInteger(h)||h<1||h>18||!Number.isInteger(gross)||gross<1||gross>30)return{ok:false,code:"INVALID_CHANGE"};const old=p.holes?.[h];if(!old)return{ok:false,code:"HOLE_NOT_FOUND"};const strokes=Number(old.strokes)||0,par=Number(old.par),score={...old,gross,status:null,net:gross-strokes,diff:gross-strokes-par};if(next.mode==="stableford")score.points=stablefordPoints(gross,par);p.holes[h]=score}if(next.mode==="match_play")next.matchPlay=correctedMatchStatus(next.players);if(next.mode==="four_ball")next.fourBall=correctedFourBallStatus(next.players);next.sideGames=correctedSideGames(next.players,next.sideGames);next.version=Number(original.version)+1;next.status="corrected";next.label="Tarjeta corregida";next.correctedAt=correctedAt;next.correction={reason:String(reason).trim(),authorizedBy:String(authorizedBy).trim(),changes:structuredClone(changes),previousSha256:original.sha256};next.appVersion=appVersion;delete next.sha256;next.sha256=await sha256(next);const versions=[...(round.officialVersions||[original]),next];return{ok:true,snapshot:next,round:{...round,sideGames:next.sideGames,status:"corrected",officialVersion:next.version,snapshotHash:next.sha256,officialSnapshot:next,officialVersions:versions}}}
  return{stableStringify:stable,sha256,sha256Sync,validate,close,closeSync,correct};
});
