(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;root.GSCScoresUI=api})(globalThis,function(root){
  'use strict';
  const logo='/assets/official-logos/golf-score-card-gt-horizontal-original.webp';
  const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function header(event,course,date){return '<header class="scores-heading"><div class="scores-heading-top"><h2>SCORES</h2><img src="'+logo+'" alt="Golf Score Card Guatemala"></div><div class="scores-event">'+escape(event)+'</div><div class="scores-meta">'+escape([course,date].filter(Boolean).join(' · '))+'</div></header>'}
  function date(value){const d=new Date(value);return Number.isFinite(d.getTime())?new Intl.DateTimeFormat('es-GT',{timeZone:'America/Guatemala',day:'numeric',month:'long',year:'numeric'}).format(d).toUpperCase():'—'}
  function holeValues(player){const holes=new Map();for(const h of Array.isArray(player?.holes)?player.holes:Object.values(player?.holes||{})){const n=Number(h?.hole);if(Number.isInteger(n)&&n>=1&&n<=18)holes.set(n,h)}return Array.from({length:18},(_,i)=>{const h=holes.get(i+1);if(!h)return '—';if(h.explicitX)return 'X/—';return (Number.isInteger(h.gross)?h.gross:'—')+'/'+(Number.isInteger(h.net)?h.net:'—')})}
  function grid(player){const values=holeValues(player);return [0,9].map(start=>'<table class="scores-nine"><thead><tr><th>HOYO</th>'+values.slice(start,start+9).map((_,i)=>'<th>'+(start+i+1)+'</th>').join('')+'</tr></thead><tbody><tr><th>G/N<small>GROSS<br>NETO</small></th>'+values.slice(start,start+9).map(value=>'<td>'+escape(value)+'</td>').join('')+'</tr></tbody></table>').join('')}
  let modal=null,returnFocus=null;
  function close(){if(!modal)return;modal.remove();modal=null;root.document.removeEventListener('keydown',keys);returnFocus?.focus({preventScroll:true})}
  function keys(event){if(event.key==='Escape'){event.preventDefault();close()}else if(event.key==='Tab'&&modal){event.preventDefault();modal.querySelector('[data-scores-close]').focus()}}
  function detail(player,snapshot,eventName){close();returnFocus=root.document.activeElement;modal=root.document.createElement('div');modal.className='scores-detail-backdrop';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-label','18 scores de '+player.name);modal.innerHTML='<section class="scores-detail"><button data-scores-close type="button" aria-label="Cerrar detalle de scores">X</button>'+header(eventName||snapshot.tournament||'',snapshot.course,date(snapshot.playedAt))+'<h3>'+escape(player.name)+'</h3><p>G/N = GROSS / NETO</p>'+grid(player)+'<p>— = HOYO SIN SCORE</p></section>';root.document.body.appendChild(modal);modal.querySelector('[data-scores-close]').onclick=close;root.document.addEventListener('keydown',keys);modal.querySelector('[data-scores-close]').focus({preventScroll:true})}
  function bindRows(target,rows){for(const node of target.querySelectorAll('[data-score-player]')){const index=Number(node.dataset.scorePlayer),row=rows[index];if(!row)continue;let last=0;node.onclick=event=>{if(event.target.closest('button,a,input,select,summary'))return;const now=Date.now();if(last&&now-last<400){last=0;detail(row.player,row.snapshot||{},row.eventName)}else last=now};node.onkeydown=event=>{if(event.target!==node)return;if(event.key==='Enter'){event.preventDefault();detail(row.player,row.snapshot||{},row.eventName)}}}}
  return {header,date,holeValues,grid,detail,close,bindRows};
});
