(function(root,factory){
  const api=factory();
  if(typeof module!=="undefined"&&module.exports)module.exports=api;
  if(root)root.GSCVegas=api;
})(typeof globalThis!=="undefined"?globalThis:this,function(){
  "use strict";

  const TEAM_NAMES=Object.freeze(["PAREJA VERDE","PAREJA ORO","PAREJA AZUL"]),round=(value,digits=2)=>{const factor=10**digits;return Math.round((Number(value)||0)*factor)/factor},validPlayers=players=>Array.isArray(players)&&[4,6].includes(players.length)&&players.every(player=>player?.id&&player?.name)?players:[];
  function normalizeConfig(value={}){return{enabled:value.enabled===true,scoreType:value.scoreType==="net"?"net":"gross",unitValue:Math.max(.01,round(value.unitValue||1,2)),birdieFlip:value.birdieFlip!==false,bothBirdies:value.bothBirdies==="both_flip"?"both_flip":"cancel",eagleDouble:value.eagleDouble===true,holeCapPoints:Math.max(1,Math.min(999,Math.trunc(Number(value.holeCapPoints)||20))),currency:value.currency==="USD"?"USD":"GTQ",tiePolicy:"push",tenPlusPolicy:"HIGH_SCORE_FIRST",settlement:"pairwise_point_difference",rulesVersion:"VEGAS_DUAL_CURRENCY_V332",variant:"CLASSIC_4_WITH_GSC_GT_6_PLAYER_ADAPTATION"}}
  const scoreAt=(player,hole,type)=>{const score=player?.holes?.[hole];if(!score)return{state:"missing",value:null,par:null,diff:null};if(score.status==="x")return{state:"x",value:null,par:Number(score.par)||null,diff:null};const value=Number(score[type]),par=Number(score.par);return Number.isFinite(value)&&Number.isFinite(par)?{state:"valid",value,par,diff:value-par}:{state:"missing",value:null,par:null,diff:null}};
  const teamIndexes=team=>[team*2,team*2+1],pairNumber=(items,flipped=false)=>{const values=items.map(item=>item.value).sort((a,b)=>a-b),forceHighFirst=values[1]>=10,ordered=flipped||forceHighFirst?[values[1],values[0]]:values;return Number(ordered.map(String).join(""))};
  function settlements(players,balances){const debtors=players.map(player=>({id:player.id,name:player.name,amount:round(-(balances[player.id]||0),2)})).filter(item=>item.amount>.009).sort((a,b)=>b.amount-a.amount),creditors=players.map(player=>({id:player.id,name:player.name,amount:round(balances[player.id]||0,2)})).filter(item=>item.amount>.009).sort((a,b)=>b.amount-a.amount),out=[];let d=0,c=0;while(d<debtors.length&&c<creditors.length){const amount=round(Math.min(debtors[d].amount,creditors[c].amount),2);if(amount)out.push({fromPlayerId:debtors[d].id,fromName:debtors[d].name,toPlayerId:creditors[c].id,toName:creditors[c].name,amount});debtors[d].amount=round(debtors[d].amount-amount,2);creditors[c].amount=round(creditors[c].amount-amount,2);if(debtors[d].amount<=.009)d++;if(creditors[c].amount<=.009)c++}return out}
  function compute(playersInput,configInput={},options={}){
    const players=validPlayers(playersInput),config=normalizeConfig(configInput),holeCount=Math.max(1,Math.min(18,Math.trunc(Number(options.holeCount)||18))),teamCount=players.length/2,teamPoints=Array(teamCount).fill(0),holes=[];
    if(!config.enabled||!players.length)return{ok:false,code:!config.enabled?"VEGAS_DISABLED":"VEGAS_REQUIRES_4_OR_6_PLAYERS",config,holes,teams:[],balances:{},metrics:{completedHoles:0,pendingHoles:0,voidHoles:0,duelsResolved:0,pushes:0,flips:0,eagleDoubles:0,cappedDuels:0,totalPointsMoved:0,moneyTransferred:0,settlementTotal:0,largestPointSwing:0,leaderNames:[]},settlements:[]};
    for(let hole=1;hole<=holeCount;hole++){
      const scores=players.map(player=>({playerId:player.id,name:player.name,...scoreAt(player,hole,config.scoreType)}));if(scores.some(score=>score.state!=="valid")){holes.push({hole,state:scores.some(score=>score.state==="missing")?"pending":"void",reason:scores.some(score=>score.state==="x")?"X_VOIDS_HOLE":"MISSING_SCORE",scores,matchups:[]});continue}
      const teams=Array.from({length:teamCount},(_,teamIndex)=>{const items=teamIndexes(teamIndex).map(index=>scores[index]),birdie=items.some(item=>item.diff<=-1),eagle=items.some(item=>item.diff<=-2);return{teamIndex,name:TEAM_NAMES[teamIndex],items,birdie,eagle,baseNumber:pairNumber(items)}}),matchups=[];
      for(let a=0;a<teamCount;a++)for(let b=a+1;b<teamCount;b++){
        const teamA=teams[a],teamB=teams[b],bothBirdie=teamA.birdie&&teamB.birdie,bothFlip=bothBirdie&&config.bothBirdies==="both_flip",flipA=config.birdieFlip&&(bothFlip||(teamB.birdie&&!teamA.birdie)),flipB=config.birdieFlip&&(bothFlip||(teamA.birdie&&!teamB.birdie)),numberA=pairNumber(teamA.items,flipA),numberB=pairNumber(teamB.items,flipB),rawDifference=Math.abs(numberA-numberB),winnerTeamIndex=numberA===numberB?null:numberA<numberB?a:b,loserTeamIndex=winnerTeamIndex===null?null:winnerTeamIndex===a?b:a,eagleMultiplier=config.eagleDouble&&winnerTeamIndex!==null&&teams[winnerTeamIndex].eagle&&!teams[loserTeamIndex].eagle?2:1,rawPoints=rawDifference*eagleMultiplier,points=winnerTeamIndex===null?0:Math.min(config.holeCapPoints,rawPoints),capApplied=points<rawPoints;
        if(winnerTeamIndex!==null){teamPoints[winnerTeamIndex]+=points;teamPoints[loserTeamIndex]-=points}matchups.push({teamIndexes:[a,b],teamNames:[teamA.name,teamB.name],numberA,numberB,flipA,flipB,bothBirdie,rawDifference,eagleMultiplier,rawPoints,points,capApplied,winnerTeamIndex,loserTeamIndex,winnerTeamName:winnerTeamIndex===null?null:teams[winnerTeamIndex].name,state:winnerTeamIndex===null?"push":"won"});
      }
      holes.push({hole,state:"complete",scores,teams,matchups,teamDeltas:teams.map((_,teamIndex)=>matchups.reduce((sum,item)=>sum+(item.winnerTeamIndex===teamIndex?item.points:item.loserTeamIndex===teamIndex?-item.points:0),0))});
    }
    const teams=Array.from({length:teamCount},(_,teamIndex)=>({teamIndex,name:TEAM_NAMES[teamIndex],playerIds:teamIndexes(teamIndex).map(index=>players[index].id),playerNames:teamIndexes(teamIndex).map(index=>players[index].name),points:teamPoints[teamIndex],balance:round(teamPoints[teamIndex]*config.unitValue,2)})),balances={};for(const team of teams)for(const id of team.playerIds)balances[id]=round(team.balance/2,2);
    const matchups=holes.flatMap(item=>item.matchups||[]),totalPointsMoved=matchups.reduce((sum,item)=>sum+item.points,0),bestPoints=Math.max(0,...teams.map(item=>item.points)),hasPosition=teams.some(item=>item.points!==bestPoints),metrics={completedHoles:holes.filter(item=>item.state==="complete").length,pendingHoles:holes.filter(item=>item.state==="pending").length,voidHoles:holes.filter(item=>item.state==="void").length,duelsResolved:matchups.filter(item=>item.state==="won").length,pushes:matchups.filter(item=>item.state==="push").length,flips:matchups.reduce((sum,item)=>sum+Number(item.flipA)+Number(item.flipB),0),eagleDoubles:matchups.filter(item=>item.eagleMultiplier===2).length,cappedDuels:matchups.filter(item=>item.capApplied).length,totalPointsMoved,moneyTransferred:round(totalPointsMoved*config.unitValue,2),settlementTotal:round(Object.values(balances).filter(value=>value>0).reduce((sum,value)=>sum+value,0),2),largestPointSwing:matchups.reduce((largest,item)=>Math.max(largest,item.points),0),maximumDuelExposure:round(config.holeCapPoints*config.unitValue,2),leaderNames:hasPosition?teams.filter(item=>item.points===bestPoints).map(item=>item.name):[]};
    return{ok:true,config,holes,teams,teamPoints,balances,metrics,settlements:settlements(players,balances)};
  }
  return Object.freeze({TEAM_NAMES,normalizeConfig,compute,scoreAt,pairNumber});
});
