import {createHash,randomBytes} from 'node:crypto';
const hash=value=>createHash('sha256').update(String(value)).digest('hex');
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const fail=(code,status=403)=>{throw Object.assign(new Error(code),{code,status})};
export function liveShareScope(sql,kind){if(!['tournament','private'].includes(kind))fail('LIVE_SHARE_KIND_INVALID',400);return kind==='tournament'?sql:(strings,...values)=>{const mapped=strings.map(s=>s.replace(/\blive_tournaments\b/g,'live_private_rounds').replace(/\blive_streams\b/g,'live_private_streams'));Object.defineProperty(mapped,'raw',{value:mapped});return sql(mapped,...values)}}
export async function ensureLiveShares(sql){await sql`CREATE TABLE IF NOT EXISTS gsc_live_shares(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),event_id uuid NOT NULL,event_kind text NOT NULL CHECK(event_kind IN ('tournament','private')),issuer_stream_id uuid NOT NULL,code_hash char(64) UNIQUE NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),expires_at timestamptz NOT NULL,consumed_at timestamptz,revoked_at timestamptz)`;await sql`CREATE TABLE IF NOT EXISTS gsc_live_share_sessions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),share_id uuid NOT NULL UNIQUE REFERENCES gsc_live_shares(id),token_hash char(64) UNIQUE NOT NULL,expires_at timestamptz NOT NULL,revoked_at timestamptz)`;await sql`CREATE TABLE IF NOT EXISTS gsc_live_share_limits(identity_hash char(64) NOT NULL,action text NOT NULL,minute timestamptz NOT NULL,count integer NOT NULL,PRIMARY KEY(identity_hash,action,minute))`}
export async function limitLiveShare(sql,req,body){const action=String(body.action||'').slice(0,20),address=String(req.headers?.['x-forwarded-for']||req.headers?.['x-real-ip']||'unknown').split(',')[0].trim(),identity=hash(address+':'+String(body.eventId||'').slice(0,36)),maximum=action==='read'?240:20;const rows=await sql`INSERT INTO gsc_live_share_limits(identity_hash,action,minute,count) VALUES(${identity},${action},date_trunc('minute',now()),1) ON CONFLICT(identity_hash,action,minute) DO UPDATE SET count=gsc_live_share_limits.count+1 RETURNING count`;if(rows[0].count>maximum)fail('LIVE_SHARE_RATE_LIMITED',429)}
export function shareCookieName(eventId){if(!uuid.test(String(eventId)))fail('LIVE_SHARE_EVENT_INVALID',400);return '__Host-gsc_live_'+eventId.replaceAll('-','')}
export function shareCookie(eventId,token,maxAge=86400){return shareCookieName(eventId)+'='+token+'; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age='+maxAge}
function sessionToken(req,eventId){const name=shareCookieName(eventId)+'=';const token=String(req.headers?.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(name))?.slice(name.length)||'';if(!/^[A-Za-z0-9_-]{43}$/.test(token))fail('LIVE_SHARE_SESSION_REQUIRED',401);return token}
export async function createLiveShare(sql,req,body){const id=String(body.eventId||'');if(!uuid.test(id))fail('LIVE_SHARE_EVENT_INVALID',400);const scoped=liveShareScope(sql,body.eventKind);const secret=String(req.headers?.authorization||'').match(/^LivePublisher ([A-Za-z0-9_-]{40,100})$/i)?.[1];if(!secret)fail('LIVE_SHARE_PLAYER_REQUIRED',403);
 const rows=await scoped`SELECT e.id,e.name,e.expires_at,s.id AS stream_id FROM live_tournaments e JOIN live_streams s ON s.tournament_id=e.id WHERE e.id=${id}::uuid AND e.status='active' AND e.expires_at>now() AND s.publisher_secret_hash=${hash(secret)} AND s.status='active' AND s.expires_at>now() AND jsonb_array_length(coalesce(s.current_snapshot->'players','[]'::jsonb))>0 LIMIT 1`;
 if(!rows.length)fail('LIVE_SHARE_PLAYER_REQUIRED',403);const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',code=[...randomBytes(12)].map(b=>alphabet[b%alphabet.length]).join('');const created=await sql`INSERT INTO gsc_live_shares(event_id,event_kind,issuer_stream_id,code_hash,expires_at) VALUES(${id}::uuid,${body.eventKind},${rows[0].stream_id}::uuid,${hash(code)},least(${rows[0].expires_at}::timestamptz,now()+interval '24 hours')) RETURNING id,expires_at`;return{ok:true,shareId:created[0].id,code,eventId:id,eventKind:body.eventKind,name:rows[0].name,expiresAt:created[0].expires_at}}
function validateEvent(event){if(!event)fail('LIVE_SHARE_EVENT_INVALID',404);if(event.status==='revoked')fail('LIVE_SHARE_REVOKED',410);if(new Date(event.expires_at)<=new Date())fail('LIVE_SHARE_EVENT_EXPIRED',410);if(event.status!=='active')fail('LIVE_SHARE_EVENT_CLOSED',410)}
export async function redeemLiveShare(sql,body){const id=String(body.eventId||'');shareCookieName(id);liveShareScope(sql,body.eventKind);const code=String(body.code||'');if(!/^[A-HJ-NP-Z2-9]{12}$/.test(code))fail('LIVE_SHARE_CODE_INVALID_OR_USED',410);const scoped=liveShareScope(sql,body.eventKind);const events=await scoped`SELECT id,status,expires_at FROM live_tournaments WHERE id=${id}::uuid LIMIT 1`;validateEvent(events[0]);
 const token=randomBytes(32).toString('base64url');const rows=await sql`WITH consumed AS (UPDATE gsc_live_shares SET consumed_at=now() WHERE event_id=${id}::uuid AND event_kind=${body.eventKind} AND code_hash=${hash(code)} AND consumed_at IS NULL AND revoked_at IS NULL AND expires_at>now() RETURNING id,expires_at) INSERT INTO gsc_live_share_sessions(share_id,token_hash,expires_at) SELECT id,${hash(token)},expires_at FROM consumed RETURNING expires_at`;
 if(!rows.length)fail('LIVE_SHARE_CODE_INVALID_OR_USED',410);return{ok:true,eventId:id,eventKind:body.eventKind,token,expiresAt:rows[0].expires_at}}
export async function readLiveShare(sql,req,body){const id=String(body.eventId||''),scoped=liveShareScope(sql,body.eventKind),token=sessionToken(req,id);const sessions=await sql`SELECT s.id,s.expires_at,s.revoked_at,g.issuer_stream_id,g.expires_at AS share_expires_at,g.revoked_at AS share_revoked_at FROM gsc_live_share_sessions s JOIN gsc_live_shares g ON g.id=s.share_id WHERE s.token_hash=${hash(token)} AND g.event_id=${id}::uuid AND g.event_kind=${body.eventKind} LIMIT 1`;if(!sessions.length)fail('LIVE_SHARE_SESSION_REQUIRED',401);if(sessions[0].revoked_at||sessions[0].share_revoked_at)fail('LIVE_SHARE_REVOKED',410);if(new Date(sessions[0].expires_at)<=new Date()||new Date(sessions[0].share_expires_at)<=new Date())fail('LIVE_SHARE_EVENT_EXPIRED',410);
 const events=await scoped`SELECT id,name,mode,status,revision,expires_at,updated_at FROM live_tournaments WHERE id=${id}::uuid LIMIT 1`;validateEvent(events[0]);const event=events[0];if(body.sinceRevision!==null&&body.sinceRevision!==undefined&&Number(body.sinceRevision)===Number(event.revision))return{ok:true,unchanged:true,revision:Number(event.revision)};const cursor=String(body.cursor||'');if(cursor&&!uuid.test(cursor))fail('LIVE_SHARE_CURSOR_INVALID',400);
 const streams=await scoped`SELECT id,scope,group_label,status,revision,expires_at,updated_at,current_snapshot FROM live_streams WHERE tournament_id=${id}::uuid AND id=${sessions[0].issuer_stream_id}::uuid AND status='active' AND expires_at>now() AND (${cursor||null}::uuid IS NULL OR id>${cursor||null}::uuid) ORDER BY id LIMIT 51`;
 return{ok:true,kind:'tournament',tournament:{id:event.id,name:event.name,mode:event.mode,status:event.status,revision:Number(event.revision),expiresAt:event.expires_at,updatedAt:event.updated_at},streams:streams.slice(0,50).map(row=>({id:row.id,scope:row.scope,groupLabel:row.group_label,status:row.status,revision:Number(row.revision),expiresAt:row.expires_at,updatedAt:row.updated_at,snapshot:row.current_snapshot})),nextCursor:streams.length>50?streams[49].id:null}}
export async function revokeLiveShare(sql,req,body){const scoped=liveShareScope(sql,body.eventKind),id=String(body.eventId||'');shareCookieName(id);if(!uuid.test(String(body.shareId||'')))fail('LIVE_SHARE_ID_INVALID',400);const secret=String(req.headers?.authorization||'').match(/^LivePublisher ([A-Za-z0-9_-]{40,100})$/i)?.[1];if(!secret)fail('LIVE_SHARE_PLAYER_REQUIRED');const streams=await scoped`SELECT id FROM live_streams WHERE tournament_id=${id}::uuid AND publisher_secret_hash=${hash(secret)} AND status='active' AND expires_at>now() LIMIT 1`;if(!streams.length)fail('LIVE_SHARE_PLAYER_REQUIRED');const rows=await sql`UPDATE gsc_live_shares SET revoked_at=now() WHERE id=${body.shareId}::uuid AND event_id=${id}::uuid AND event_kind=${body.eventKind} AND issuer_stream_id=${streams[0].id}::uuid RETURNING id`;if(!rows.length)fail('LIVE_SHARE_FORBIDDEN');return{ok:true}}
