import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
const {chromium}=await import('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const root=process.cwd(),out=path.join(root,'CONTROL_PROYECTO_SCIRE/EVIDENCIAS_R162');fs.mkdirSync(out,{recursive:true});const id='11111111-1111-4111-8111-111111111111';
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/')){let body='';req.on('data',c=>body+=c);req.on('end',()=>{let data={};try{data=JSON.parse(body)}catch{}let result={ok:true,personalCode:'qa-r159',accountCode:'qa-r159',events:[],aliases:[],authenticated:false};if(url.pathname==='/api/event-administration'&&data.action==='list')result={ok:true,owner:false,accountCode:'qa-r159',events:[{id,event_kind:'tournament',name:'Family',status:'active',authority:'creator'}]};else if(data.action==='list')result={...result,events:[{eventId:id,eventKind:'tournament',name:'Family',role:'organizer',status:'active',players:[{id:'p1',name:'QA',tournamentCategory:'b'}]}]};if(data.action==='read')result={ok:true,membership:{role:'organizer',players:[{id:'p1',name:'QA',tournamentCategory:'b'}]},tournament:{name:'Family',status:'active',configuration:{},revision:1},streams:[]};if(data.action==='inspect-tournament-code'||data.action==='join-code')result={ok:true,eventId:id,eventKind:'tournament',name:'Family',joinCode:'QA23456789',configuration:{course:'EL PULTÉ GOLF',mode:'general',categories:['b']}};if(data.action==='organizer-entry-code')result={ok:true,joinCode:'QA23456789'};if(data.action==='create')result={ok:true,eventId:id,eventKind:data.eventKind,name:data.name,joinCode:'QA23456789',configuration:{creatorName:data.creatorName},expiresAt:'2099-01-01'};res.setHeader('Content-Type','application/json');res.end(JSON.stringify(result))});return}const file=path.resolve(root,'.'+url.pathname);res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.webp':'image/webp','.png':'image/png'})[path.extname(file)]||'application/octet-stream');try{res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end('{}')}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({executablePath:'/tmp/r159-chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const evidence={release:'R162',type:'LOCAL_REAL_CHROMIUM_QA_FIXTURES',physicalIphone:false,whatsappDelivered:false,cases:[],errors:[]};
try{for(const width of [390,430]){
const ctx=await browser.newContext({viewport:{width,height:width*2},isMobile:true,hasTouch:true,deviceScaleFactor:2160/width,serviceWorkers:'block'});await ctx.addInitScript(()=>{window.QAShares=[];navigator.share=async data=>QAShares.push(data)});const page=await ctx.newPage();page.on('pageerror',error=>evidence.errors.push(error.message));await page.goto(base+'/index-grupal.html?inicio=1');
await page.evaluate(id=>{navigator.clipboard.writeText=async value=>window.QACopied=value;window.GSCPersonalEvents.presentCreatedTournament({eventId:id,name:'Family',joinCode:'QA23456789'});},id);
await page.evaluate(()=>GSCPersonalEvents.organizerInvitations());assert.equal(await page.locator('[data-tournament-code]').innerText(),'QA23456789');await page.locator('[data-copy-owned-code]').click();assert.equal(await page.evaluate(()=>QACopied),'QA23456789');await page.locator('[data-share-owned-code]').click();await page.locator('[data-send-invitation]').click();assert((await page.evaluate(()=>QAShares.at(-1).text)).endsWith('QA23456789'));
await page.reload();await page.evaluate(()=>GSCPersonalEvents.organizerInvitations());assert.equal(await page.locator('[data-tournament-code]').innerText(),'QA23456789');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const shot=path.join(out,width+'-ids.png');await page.screenshot({path:shot});evidence.cases.push({width,test:'Organizer ID persists across reload, copy and single WhatsApp share',status:'PASS',sha256:createHash('sha256').update(fs.readFileSync(shot)).digest('hex')});await page.goto(base+'/event-administration.html');await page.waitForSelector('[data-copy-tournament]');assert.equal(await page.locator('#events output').innerText(),'QA23456789');await page.locator('[data-share-tournament]').click();await page.locator('[data-send-invitation]').waitFor({state:'visible'});evidence.cases.push({width,test:'Administration keeps delete and single-use ID share actions',status:'PASS'});
await page.goto(base+'/index-grupal.html?inicio=1');await page.evaluate(()=>localStorage.clear());await page.reload();await page.locator('#registrationJoinTournament').click();await page.locator('#activeTournamentCode').waitFor();assert.equal(await page.evaluate(()=>document.activeElement.id==='activeTournamentCode'),false);await page.locator('#activeTournamentCode').fill('QA23456789');await page.locator('[data-inspect-tournament]').click();await page.waitForFunction(()=>!!localStorage.getItem('gsc-tournament-entry-draft-v1'));assert.equal(await page.evaluate(()=>round.configured),false);await page.locator('[data-draft-name="0"]').fill('QA');await page.locator('[data-draft-category="0"]').selectOption('b');await page.locator('[data-draft-hcp="0"]').fill('14');await page.locator('[data-draft-tee="0"]').selectOption('Blanco');await page.locator('#setupOk').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('gsc-tournament-connect-selection-v1')||'null')?.registrationApproved===true);assert.equal(await page.evaluate(()=>localStorage.getItem('gsc-tournament-entry-draft-v1')),null);await page.locator('#startRoundButton').click();assert.equal(await page.evaluate(()=>round.personalEventId),id);evidence.cases.push({width,test:'Code before players → register → OK consumes → official start binds tournament',status:'PASS'});
await page.evaluate(()=>localStorage.clear());await page.goto(base+'/index-grupal.html?inicio=1');await page.locator('[data-draft-name="0"]').fill('QA');await page.locator('[data-draft-category="0"]').selectOption('b');await page.locator('[data-draft-hcp="0"]').fill('14');await page.locator('[data-draft-tee="0"]').selectOption('Blanco');await page.locator('#registrationJoinTournament').click();await page.locator('[data-join-active]').waitFor();evidence.cases.push({width,test:'Players before code retains original tournament entry',status:'PASS'});await ctx.close()}
assert.equal(evidence.errors.length,0);evidence.status='PASS'}catch(error){evidence.status='FAIL';evidence.failure=error.stack;console.error(error.stack);process.exitCode=1}finally{fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify(evidence,null,2)+'\n');await browser.close();server.close()}
