import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
const {chromium}=await import('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const root=process.cwd(),out=path.join(root,'CONTROL_PROYECTO_SCIRE/EVIDENCIAS_R161');fs.mkdirSync(out,{recursive:true});const id='11111111-1111-4111-8111-111111111111';
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/')){let body='';req.on('data',c=>body+=c);req.on('end',()=>{let data={};try{data=JSON.parse(body)}catch{}let result={ok:true,personalCode:'qa-r159',accountCode:'qa-r159',events:[],aliases:[],authenticated:false};if(data.action==='list')result={...result,events:[{eventId:id,eventKind:'tournament',name:'Family',role:'player',players:[{id:'p1',name:'QA',tournamentCategory:'b'}]}]};if(data.action==='read')result={ok:true,membership:{role:'player',players:[{id:'p1',name:'QA',tournamentCategory:'b'}]},tournament:{name:'Family',configuration:{},revision:1},streams:[]};if(data.action==='create')result={ok:true,eventId:id,eventKind:data.eventKind,name:data.name,joinCode:'QA23456789',configuration:{creatorName:data.creatorName},expiresAt:'2099-01-01'};res.setHeader('Content-Type','application/json');res.end(JSON.stringify(result))});return}const file=path.resolve(root,'.'+url.pathname);res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.webp':'image/webp','.png':'image/png'})[path.extname(file)]||'application/octet-stream');try{res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end('{}')}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({executablePath:'/tmp/r159-chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const evidence={release:'R161',type:'LOCAL_REAL_CHROMIUM_QA_FIXTURES',physicalIphone:false,whatsappDelivered:false,cases:[],errors:[]};
try{for(const width of [390,430]){const ctx=await browser.newContext({viewport:{width,height:width*2},isMobile:true,hasTouch:true,deviceScaleFactor:2160/width,serviceWorkers:'block'});await ctx.addInitScript(()=>{window.QAShares=[];navigator.share=async data=>{if(window.QACancel)throw Object.assign(Error('QA cancel'),{name:'AbortError'});window.QAShares.push(data)}});const page=await ctx.newPage();page.on('pageerror',error=>evidence.errors.push(error.message));
await page.goto(base+'/index-grupal.html?inicio=1');await page.evaluate(()=>GSCPersonalEvents.joinTournament({configured:true,course:'El Pulté',mode:'general',players:[{id:'qa',name:'QA',handicap:10,tee:'Blanco',tournamentCategory:'a',holes:{}}]},()=>true));assert.equal(await page.locator('#activeTournamentCode').isVisible(),true);assert.equal(await page.evaluate(()=>document.activeElement.id==='activeTournamentCode'),false,'No automatic code focus');await page.locator('#activeTournamentCode').click();assert.equal(await page.evaluate(()=>document.activeElement.id),'activeTournamentCode');await page.locator('#activeTournamentCode').fill('QA23456789');assert.equal(await page.evaluate(()=>document.querySelector('#activeTournamentCode').value),'QA23456789');evidence.cases.push({width,test:'TORNEO opens without input focus; tap permits typing',status:'PASS'});
for(const kind of ['private','tournament']){
 await page.goto(base+'/index-grupal.html?inicio=1');
 if(kind==='private'){await page.evaluate(()=>GSCPersonalEvents.createPrivate(null,{course:'El Pulté'}));await page.locator('#personalRoundCreator').fill('Jaime Kirste');await page.locator('#personalRoundName').fill('Grupo QA');await page.locator('[data-create-private]').click()}
 else await page.evaluate(id=>GSCPersonalEvents.presentCreatedTournament({eventId:id,name:'Torneo QA',joinCode:'QA23456789',configuration:{creatorName:'Jaime Kirste'}}),id);
 await page.locator('[data-share-private-round]').click();assert.equal(await page.locator('[data-send-code]').count(),0);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 const shot=path.join(out,width+'-'+kind+'.png');await page.screenshot({path:shot});await page.locator('[data-send-invitation]').click();assert.deepEqual(await page.evaluate(()=>QAShares),[{text:'GOLF SCORE CARD GT\nTe ha invitado a participar en '+(kind==='private'?'el grupo de Jaime Kirste':'el torneo Torneo QA')+'.\nCopia y pega el código en la pantalla inicial de registro.\n'+base+'/index-grupal.html?inicio=1\n\nMODALIDAD\n'+(kind==='private'?'MI GRUPO':'TORNEO')+'\nCódigo\n\n\nQA23456789'}]);
 evidence.cases.push({width,kind,test:'one share with invitation, two blank lines, code last',screenshot:path.relative(root,shot),sha256:createHash('sha256').update(fs.readFileSync(shot)).digest('hex'),status:'PASS'});console.log('PASS',width,kind,'single message');await page.locator('[data-close-whatsapp]').click();

}
await page.goto(base+'/live-hub.html?shortcut=scores&personalKind=tournament&personalEvent='+id);await page.waitForFunction(()=>document.querySelector('#hubTournamentShelf').classList.contains('hidden'));assert.equal(await page.locator('#hubTournamentCards').isVisible(),false);assert.equal(await page.locator('#hubShowGeneral').isVisible(),true);evidence.cases.push({width,test:'direct enrolled Family scores without tournament chooser',status:'PASS'});await page.goto(base+'/live-hub.html?directory=1');await page.waitForFunction(()=>!document.querySelector('#hubTournamentShelf').classList.contains('hidden'));assert.equal(await page.locator('#hubTournamentCards').isVisible(),true);evidence.cases.push({width,test:'Menu directory remains separate',status:'PASS'});
await page.goto(base+'/event-administration.html');assert.equal(await page.getByRole('heading',{name:'ADMINISTRAR TORNEOS Y GRUPOS',exact:true}).innerText(),'ADMINISTRAR TORNEOS Y GRUPOS');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,width+'-administrar.png')});await page.locator('#gscShortcutsButton').click();assert.equal(await page.locator('[data-shortcut=administration]').count(),0);await page.locator('[data-shortcut=organizer]').click();assert(await page.locator('[data-shortcut=administration]').isVisible());await page.locator('[data-shortcut=administration]').click();assert.equal(await page.getByRole('heading',{name:'ADMINISTRAR TORNEOS Y GRUPOS',exact:true}).innerText(),'ADMINISTRAR TORNEOS Y GRUPOS');evidence.cases.push({width,test:'Administration title and menu matching; no overflow',status:'PASS'});await ctx.close()}
assert.equal(evidence.errors.length,0,evidence.errors.join(';'));evidence.status='PASS'}catch(error){evidence.status='FAIL';evidence.failure=error.stack;console.error(error.stack);process.exitCode=1}finally{fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify(evidence,null,2)+'\n');await browser.close();server.close()}
